unit Raylib.OpenGL;

{$i raylib.inc}

interface

uses
  Raylib.Core,
  { Free pascal units }
  SysUtils, Classes;

var
  glVersionMajor, glVersionMinor: Integer;

type
  GLVULKANPROCNV = pointer;
  GLbitfield = uint32;
  GLboolean = byte;
  GLbyte = int8;
  GLchar = char;
  GLcharARB = byte;
  GLclampd = double;
  GLclampf = single;
  GLclampx = int32;
  GLdouble = double;
  GLeglClientBufferEXT = pointer;
  GLeglImageOES = pointer;
  GLenum = uint32;
  GLfixed = int32;
  GLfloat = single;
  GLhalf = uint16;
  GLhalfARB = uint16;
  GLhalfNV = uint16;
  GLhandleARB = uint32;
  GLint = int32;
  GLint64 = int64;
  GLint64EXT = int64;
  GLintptr = int32;
  GLintptrARB = int32;
  GLshort = int16;
  GLsizei = int32;
  GLsizeiptr = int32;
  GLsizeiptrARB = int32;
  GLsync = pointer;
  GLubyte = uint8;
  GLuint = uint32;
  GLuint64 = uint64;
  GLuint64EXT = uint64;
  GLushort = uint16;
  GLvdpauSurfaceNV = int32;
  GLvoid = pointer;
  _cl_context = pointer;
  _cl_event = pointer;

  PGLVULKANPROCNV = ^pointer;
  PGLbitfield = ^uint32;
  PGLboolean = ^byte;
  PGLbyte = ^int8;
  PGLchar = ^char;
  PGLcharARB = ^byte;
  PGLclampd = ^double;
  PGLclampf = ^single;
  PGLclampx = ^int32;
  PGLdouble = ^double;
  PGLeglClientBufferEXT = ^pointer;
  PGLeglImageOES = ^pointer;
  PGLenum = ^uint32;
  PGLfixed = ^int32;
  PGLfloat = ^single;
  PGLhalf = ^uint16;
  PGLhalfARB = ^uint16;
  PGLhalfNV = ^uint16;
  PGLhandleARB = ^uint32;
  PGLint = ^int32;
  PGLint64 = ^int64;
  PGLint64EXT = ^int64;
  PGLintptr = ^int32;
  PGLintptrARB = ^int32;
  PGLshort = ^int16;
  PGLsizei = ^int32;
  PGLsizeiptr = ^int32;
  PGLsizeiptrARB = ^int32;
  PGLsync = ^pointer;
  PGLubyte = ^uint8;
  PGLuint = ^uint32;
  PGLuint64 = ^uint64;
  PGLuint64EXT = ^uint64;
  PGLushort = ^uint16;
  PGLvdpauSurfaceNV = ^int32;
  PGLvoid = ^pointer;
  P_cl_context = ^pointer;
  P_cl_event = ^pointer;
  PPGLchar = ^PGLchar;
  PPGLcharARB = ^PGLcharARB;
  PPGLboolean = ^PGLboolean;

  GLdebugProc = procedure (
    source: GLenum;
    typ: GLenum;
    id: GLuint;
    severity: GLenum;
    length: GLsizei;
    message: PGLchar;
    userParam: pointer); stdcall;
  GLdebugProcArb = GLdebugProc;
  GLdebugProcKhr = GLdebugProc;

  GLdebugProcAmd = procedure (
    id: GLuint;
    category: GLenum;
    severity: GLenum;
    len: GLsizei;
    message: PGLchar;
    userParam: pointer); stdcall;

const
  GL_FALSE = 0;
  GL_INVALID_INDEX = uint32($FFFFFFFF);
  GL_NONE = 0;
  GL_NONE_OES = 0;
  GL_NO_ERROR = 0;
  GL_ONE = 1;
  GL_TIMEOUT_IGNORED = uint64($FFFFFFFFFFFFFFFF);
  GL_TIMEOUT_IGNORED_APPLE = uint64($FFFFFFFFFFFFFFFF);
  GL_TRUE = 1;
  GL_VERSION_ES_CL_1_0 = 1;
  GL_VERSION_ES_CL_1_1 = 1;
  GL_VERSION_ES_CM_1_1 = 1;
  GL_ZERO = 0;

  GL_DEPTH_BUFFER_BIT = $00000100;
  GL_STENCIL_BUFFER_BIT = $00000400;
  GL_COLOR_BUFFER_BIT = $00004000;
  GL_POINTS = $0000;
  GL_LINES = $0001;
  GL_LINE_LOOP = $0002;
  GL_LINE_STRIP = $0003;
  GL_TRIANGLES = $0004;
  GL_TRIANGLE_STRIP = $0005;
  GL_TRIANGLE_FAN = $0006;
  GL_NEVER = $0200;
  GL_LESS = $0201;
  GL_EQUAL = $0202;
  GL_LEQUAL = $0203;
  GL_GREATER = $0204;
  GL_NOTEQUAL = $0205;
  GL_GEQUAL = $0206;
  GL_ALWAYS = $0207;
  GL_SRC_COLOR = $0300;
  GL_ONE_MINUS_SRC_COLOR = $0301;
  GL_SRC_ALPHA = $0302;
  GL_ONE_MINUS_SRC_ALPHA = $0303;
  GL_DST_ALPHA = $0304;
  GL_ONE_MINUS_DST_ALPHA = $0305;
  GL_DST_COLOR = $0306;
  GL_ONE_MINUS_DST_COLOR = $0307;
  GL_SRC_ALPHA_SATURATE = $0308;
  GL_FRONT_LEFT = $0400;
  GL_FRONT_RIGHT = $0401;
  GL_BACK_LEFT = $0402;
  GL_BACK_RIGHT = $0403;
  GL_FRONT = $0404;
  GL_BACK = $0405;
  GL_LEFT = $0406;
  GL_RIGHT = $0407;
  GL_FRONT_AND_BACK = $0408;
  GL_INVALID_ENUM = $0500;
  GL_INVALID_VALUE = $0501;
  GL_INVALID_OPERATION = $0502;
  GL_OUT_OF_MEMORY = $0505;
  GL_CW = $0900;
  GL_CCW = $0901;
  GL_POINT_SIZE = $0B11;
  GL_POINT_SIZE_RANGE = $0B12;
  GL_POINT_SIZE_GRANULARITY = $0B13;
  GL_LINE_SMOOTH = $0B20;
  GL_LINE_WIDTH = $0B21;
  GL_LINE_WIDTH_RANGE = $0B22;
  GL_LINE_WIDTH_GRANULARITY = $0B23;
  GL_POLYGON_MODE = $0B40;
  GL_POLYGON_SMOOTH = $0B41;
  GL_CULL_FACE = $0B44;
  GL_CULL_FACE_MODE = $0B45;
  GL_FRONT_FACE = $0B46;
  GL_DEPTH_RANGE = $0B70;
  GL_DEPTH_TEST = $0B71;
  GL_DEPTH_WRITEMASK = $0B72;
  GL_DEPTH_CLEAR_VALUE = $0B73;
  GL_DEPTH_FUNC = $0B74;
  GL_STENCIL_TEST = $0B90;
  GL_STENCIL_CLEAR_VALUE = $0B91;
  GL_STENCIL_FUNC = $0B92;
  GL_STENCIL_VALUE_MASK = $0B93;
  GL_STENCIL_FAIL = $0B94;
  GL_STENCIL_PASS_DEPTH_FAIL = $0B95;
  GL_STENCIL_PASS_DEPTH_PASS = $0B96;
  GL_STENCIL_REF = $0B97;
  GL_STENCIL_WRITEMASK = $0B98;
  GL_VIEWPORT = $0BA2;
  GL_DITHER = $0BD0;
  GL_BLEND_DST = $0BE0;
  GL_BLEND_SRC = $0BE1;
  GL_BLEND = $0BE2;
  GL_LOGIC_OP_MODE = $0BF0;
  GL_DRAW_BUFFER = $0C01;
  GL_READ_BUFFER = $0C02;
  GL_SCISSOR_BOX = $0C10;
  GL_SCISSOR_TEST = $0C11;
  GL_COLOR_CLEAR_VALUE = $0C22;
  GL_COLOR_WRITEMASK = $0C23;
  GL_DOUBLEBUFFER = $0C32;
  GL_STEREO = $0C33;
  GL_LINE_SMOOTH_HINT = $0C52;
  GL_POLYGON_SMOOTH_HINT = $0C53;
  GL_UNPACK_SWAP_BYTES = $0CF0;
  GL_UNPACK_LSB_FIRST = $0CF1;
  GL_UNPACK_ROW_LENGTH = $0CF2;
  GL_UNPACK_SKIP_ROWS = $0CF3;
  GL_UNPACK_SKIP_PIXELS = $0CF4;
  GL_UNPACK_ALIGNMENT = $0CF5;
  GL_PACK_SWAP_BYTES = $0D00;
  GL_PACK_LSB_FIRST = $0D01;
  GL_PACK_ROW_LENGTH = $0D02;
  GL_PACK_SKIP_ROWS = $0D03;
  GL_PACK_SKIP_PIXELS = $0D04;
  GL_PACK_ALIGNMENT = $0D05;
  GL_MAX_TEXTURE_SIZE = $0D33;
  GL_MAX_VIEWPORT_DIMS = $0D3A;
  GL_SUBPIXEL_BITS = $0D50;
  GL_TEXTURE_1D = $0DE0;
  GL_TEXTURE_2D = $0DE1;
  GL_TEXTURE_WIDTH = $1000;
  GL_TEXTURE_HEIGHT = $1001;
  GL_TEXTURE_BORDER_COLOR = $1004;
  GL_DONT_CARE = $1100;
  GL_FASTEST = $1101;
  GL_NICEST = $1102;
  GL_BYTE = $1400;
  GL_UNSIGNED_BYTE = $1401;
  GL_SHORT = $1402;
  GL_UNSIGNED_SHORT = $1403;
  GL_INT = $1404;
  GL_UNSIGNED_INT = $1405;
  GL_FLOAT = $1406;
  GL_CLEAR = $1500;
  GL_AND = $1501;
  GL_AND_REVERSE = $1502;
  GL_COPY = $1503;
  GL_AND_INVERTED = $1504;
  GL_NOOP = $1505;
  GL_XOR = $1506;
  GL_OR = $1507;
  GL_NOR = $1508;
  GL_EQUIV = $1509;
  GL_INVERT = $150A;
  GL_OR_REVERSE = $150B;
  GL_COPY_INVERTED = $150C;
  GL_OR_INVERTED = $150D;
  GL_NAND = $150E;
  GL_SET = $150F;
  GL_TEXTURE = $1702;
  GL_COLOR = $1800;
  GL_DEPTH = $1801;
  GL_STENCIL = $1802;
  GL_STENCIL_INDEX = $1901;
  GL_DEPTH_COMPONENT = $1902;
  GL_RED = $1903;
  GL_GREEN = $1904;
  GL_BLUE = $1905;
  GL_ALPHA = $1906;
  GL_RGB = $1907;
  GL_RGBA = $1908;
  GL_POINT = $1B00;
  GL_LINE = $1B01;
  GL_FILL = $1B02;
  GL_KEEP = $1E00;
  GL_REPLACE = $1E01;
  GL_INCR = $1E02;
  GL_DECR = $1E03;
  GL_VENDOR = $1F00;
  GL_RENDERER = $1F01;
  GL_VERSION = $1F02;
  GL_EXTENSIONS = $1F03;
  GL_NEAREST = $2600;
  GL_LINEAR = $2601;
  GL_NEAREST_MIPMAP_NEAREST = $2700;
  GL_LINEAR_MIPMAP_NEAREST = $2701;
  GL_NEAREST_MIPMAP_LINEAR = $2702;
  GL_LINEAR_MIPMAP_LINEAR = $2703;
  GL_TEXTURE_MAG_FILTER = $2800;
  GL_TEXTURE_MIN_FILTER = $2801;
  GL_TEXTURE_WRAP_S = $2802;
  GL_TEXTURE_WRAP_T = $2803;
  GL_REPEAT = $2901;
  GL_COLOR_LOGIC_OP = $0BF2;
  GL_POLYGON_OFFSET_UNITS = $2A00;
  GL_POLYGON_OFFSET_POINT = $2A01;
  GL_POLYGON_OFFSET_LINE = $2A02;
  GL_POLYGON_OFFSET_FILL = $8037;
  GL_POLYGON_OFFSET_FACTOR = $8038;
  GL_TEXTURE_BINDING_1D = $8068;
  GL_TEXTURE_BINDING_2D = $8069;
  GL_TEXTURE_INTERNAL_FORMAT = $1003;
  GL_TEXTURE_RED_SIZE = $805C;
  GL_TEXTURE_GREEN_SIZE = $805D;
  GL_TEXTURE_BLUE_SIZE = $805E;
  GL_TEXTURE_ALPHA_SIZE = $805F;
  GL_DOUBLE = $140A;
  GL_PROXY_TEXTURE_1D = $8063;
  GL_PROXY_TEXTURE_2D = $8064;
  GL_R3_G3_B2 = $2A10;
  GL_RGB4 = $804F;
  GL_RGB5 = $8050;
  GL_RGB8 = $8051;
  GL_RGB10 = $8052;
  GL_RGB12 = $8053;
  GL_RGB16 = $8054;
  GL_RGBA2 = $8055;
  GL_RGBA4 = $8056;
  GL_RGB5_A1 = $8057;
  GL_RGBA8 = $8058;
  GL_RGB10_A2 = $8059;
  GL_RGBA12 = $805A;
  GL_RGBA16 = $805B;
  GL_UNSIGNED_BYTE_3_3_2 = $8032;
  GL_UNSIGNED_SHORT_4_4_4_4 = $8033;
  GL_UNSIGNED_SHORT_5_5_5_1 = $8034;
  GL_UNSIGNED_INT_8_8_8_8 = $8035;
  GL_UNSIGNED_INT_10_10_10_2 = $8036;
  GL_TEXTURE_BINDING_3D = $806A;
  GL_PACK_SKIP_IMAGES = $806B;
  GL_PACK_IMAGE_HEIGHT = $806C;
  GL_UNPACK_SKIP_IMAGES = $806D;
  GL_UNPACK_IMAGE_HEIGHT = $806E;
  GL_TEXTURE_3D = $806F;
  GL_PROXY_TEXTURE_3D = $8070;
  GL_TEXTURE_DEPTH = $8071;
  GL_TEXTURE_WRAP_R = $8072;
  GL_MAX_3D_TEXTURE_SIZE = $8073;
  GL_UNSIGNED_BYTE_2_3_3_REV = $8362;
  GL_UNSIGNED_SHORT_5_6_5 = $8363;
  GL_UNSIGNED_SHORT_5_6_5_REV = $8364;
  GL_UNSIGNED_SHORT_4_4_4_4_REV = $8365;
  GL_UNSIGNED_SHORT_1_5_5_5_REV = $8366;
  GL_UNSIGNED_INT_8_8_8_8_REV = $8367;
  GL_UNSIGNED_INT_2_10_10_10_REV = $8368;
  GL_BGR = $80E0;
  GL_BGRA = $80E1;
  GL_MAX_ELEMENTS_VERTICES = $80E8;
  GL_MAX_ELEMENTS_INDICES = $80E9;
  GL_CLAMP_TO_EDGE = $812F;
  GL_TEXTURE_MIN_LOD = $813A;
  GL_TEXTURE_MAX_LOD = $813B;
  GL_TEXTURE_BASE_LEVEL = $813C;
  GL_TEXTURE_MAX_LEVEL = $813D;
  GL_SMOOTH_POINT_SIZE_RANGE = $0B12;
  GL_SMOOTH_POINT_SIZE_GRANULARITY = $0B13;
  GL_SMOOTH_LINE_WIDTH_RANGE = $0B22;
  GL_SMOOTH_LINE_WIDTH_GRANULARITY = $0B23;
  GL_ALIASED_LINE_WIDTH_RANGE = $846E;
  GL_TEXTURE0 = $84C0;
  GL_TEXTURE1 = $84C1;
  GL_TEXTURE2 = $84C2;
  GL_TEXTURE3 = $84C3;
  GL_TEXTURE4 = $84C4;
  GL_TEXTURE5 = $84C5;
  GL_TEXTURE6 = $84C6;
  GL_TEXTURE7 = $84C7;
  GL_TEXTURE8 = $84C8;
  GL_TEXTURE9 = $84C9;
  GL_TEXTURE10 = $84CA;
  GL_TEXTURE11 = $84CB;
  GL_TEXTURE12 = $84CC;
  GL_TEXTURE13 = $84CD;
  GL_TEXTURE14 = $84CE;
  GL_TEXTURE15 = $84CF;
  GL_TEXTURE16 = $84D0;
  GL_TEXTURE17 = $84D1;
  GL_TEXTURE18 = $84D2;
  GL_TEXTURE19 = $84D3;
  GL_TEXTURE20 = $84D4;
  GL_TEXTURE21 = $84D5;
  GL_TEXTURE22 = $84D6;
  GL_TEXTURE23 = $84D7;
  GL_TEXTURE24 = $84D8;
  GL_TEXTURE25 = $84D9;
  GL_TEXTURE26 = $84DA;
  GL_TEXTURE27 = $84DB;
  GL_TEXTURE28 = $84DC;
  GL_TEXTURE29 = $84DD;
  GL_TEXTURE30 = $84DE;
  GL_TEXTURE31 = $84DF;
  GL_ACTIVE_TEXTURE = $84E0;
  GL_MULTISAMPLE = $809D;
  GL_SAMPLE_ALPHA_TO_COVERAGE = $809E;
  GL_SAMPLE_ALPHA_TO_ONE = $809F;
  GL_SAMPLE_COVERAGE = $80A0;
  GL_SAMPLE_BUFFERS = $80A8;
  GL_SAMPLES = $80A9;
  GL_SAMPLE_COVERAGE_VALUE = $80AA;
  GL_SAMPLE_COVERAGE_INVERT = $80AB;
  GL_TEXTURE_CUBE_MAP = $8513;
  GL_TEXTURE_BINDING_CUBE_MAP = $8514;
  GL_TEXTURE_CUBE_MAP_POSITIVE_X = $8515;
  GL_TEXTURE_CUBE_MAP_NEGATIVE_X = $8516;
  GL_TEXTURE_CUBE_MAP_POSITIVE_Y = $8517;
  GL_TEXTURE_CUBE_MAP_NEGATIVE_Y = $8518;
  GL_TEXTURE_CUBE_MAP_POSITIVE_Z = $8519;
  GL_TEXTURE_CUBE_MAP_NEGATIVE_Z = $851A;
  GL_PROXY_TEXTURE_CUBE_MAP = $851B;
  GL_MAX_CUBE_MAP_TEXTURE_SIZE = $851C;
  GL_COMPRESSED_RGB = $84ED;
  GL_COMPRESSED_RGBA = $84EE;
  GL_TEXTURE_COMPRESSION_HINT = $84EF;
  GL_TEXTURE_COMPRESSED_IMAGE_SIZE = $86A0;
  GL_TEXTURE_COMPRESSED = $86A1;
  GL_NUM_COMPRESSED_TEXTURE_FORMATS = $86A2;
  GL_COMPRESSED_TEXTURE_FORMATS = $86A3;
  GL_CLAMP_TO_BORDER = $812D;
  GL_BLEND_DST_RGB = $80C8;
  GL_BLEND_SRC_RGB = $80C9;
  GL_BLEND_DST_ALPHA = $80CA;
  GL_BLEND_SRC_ALPHA = $80CB;
  GL_POINT_FADE_THRESHOLD_SIZE = $8128;
  GL_DEPTH_COMPONENT16 = $81A5;
  GL_DEPTH_COMPONENT24 = $81A6;
  GL_DEPTH_COMPONENT32 = $81A7;
  GL_MIRRORED_REPEAT = $8370;
  GL_MAX_TEXTURE_LOD_BIAS = $84FD;
  GL_TEXTURE_LOD_BIAS = $8501;
  GL_INCR_WRAP = $8507;
  GL_DECR_WRAP = $8508;
  GL_TEXTURE_DEPTH_SIZE = $884A;
  GL_TEXTURE_COMPARE_MODE = $884C;
  GL_TEXTURE_COMPARE_FUNC = $884D;
  GL_BLEND_COLOR = $8005;
  GL_BLEND_EQUATION = $8009;
  GL_CONSTANT_COLOR = $8001;
  GL_ONE_MINUS_CONSTANT_COLOR = $8002;
  GL_CONSTANT_ALPHA = $8003;
  GL_ONE_MINUS_CONSTANT_ALPHA = $8004;
  GL_FUNC_ADD = $8006;
  GL_FUNC_REVERSE_SUBTRACT = $800B;
  GL_FUNC_SUBTRACT = $800A;
  GL_MIN = $8007;
  GL_MAX = $8008;
  GL_BUFFER_SIZE = $8764;
  GL_BUFFER_USAGE = $8765;
  GL_QUERY_COUNTER_BITS = $8864;
  GL_CURRENT_QUERY = $8865;
  GL_QUERY_RESULT = $8866;
  GL_QUERY_RESULT_AVAILABLE = $8867;
  GL_ARRAY_BUFFER = $8892;
  GL_ELEMENT_ARRAY_BUFFER = $8893;
  GL_ARRAY_BUFFER_BINDING = $8894;
  GL_ELEMENT_ARRAY_BUFFER_BINDING = $8895;
  GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING = $889F;
  GL_READ_ONLY = $88B8;
  GL_WRITE_ONLY = $88B9;
  GL_READ_WRITE = $88BA;
  GL_BUFFER_ACCESS = $88BB;
  GL_BUFFER_MAPPED = $88BC;
  GL_BUFFER_MAP_POINTER = $88BD;
  GL_STREAM_DRAW = $88E0;
  GL_STREAM_READ = $88E1;
  GL_STREAM_COPY = $88E2;
  GL_STATIC_DRAW = $88E4;
  GL_STATIC_READ = $88E5;
  GL_STATIC_COPY = $88E6;
  GL_DYNAMIC_DRAW = $88E8;
  GL_DYNAMIC_READ = $88E9;
  GL_DYNAMIC_COPY = $88EA;
  GL_SAMPLES_PASSED = $8914;
  GL_SRC1_ALPHA = $8589;
  GL_BLEND_EQUATION_RGB = $8009;
  GL_VERTEX_ATTRIB_ARRAY_ENABLED = $8622;
  GL_VERTEX_ATTRIB_ARRAY_SIZE = $8623;
  GL_VERTEX_ATTRIB_ARRAY_STRIDE = $8624;
  GL_VERTEX_ATTRIB_ARRAY_TYPE = $8625;
  GL_CURRENT_VERTEX_ATTRIB = $8626;
  GL_VERTEX_PROGRAM_POINT_SIZE = $8642;
  GL_VERTEX_ATTRIB_ARRAY_POINTER = $8645;
  GL_STENCIL_BACK_FUNC = $8800;
  GL_STENCIL_BACK_FAIL = $8801;
  GL_STENCIL_BACK_PASS_DEPTH_FAIL = $8802;
  GL_STENCIL_BACK_PASS_DEPTH_PASS = $8803;
  GL_MAX_DRAW_BUFFERS = $8824;
  GL_DRAW_BUFFER0 = $8825;
  GL_DRAW_BUFFER1 = $8826;
  GL_DRAW_BUFFER2 = $8827;
  GL_DRAW_BUFFER3 = $8828;
  GL_DRAW_BUFFER4 = $8829;
  GL_DRAW_BUFFER5 = $882A;
  GL_DRAW_BUFFER6 = $882B;
  GL_DRAW_BUFFER7 = $882C;
  GL_DRAW_BUFFER8 = $882D;
  GL_DRAW_BUFFER9 = $882E;
  GL_DRAW_BUFFER10 = $882F;
  GL_DRAW_BUFFER11 = $8830;
  GL_DRAW_BUFFER12 = $8831;
  GL_DRAW_BUFFER13 = $8832;
  GL_DRAW_BUFFER14 = $8833;
  GL_DRAW_BUFFER15 = $8834;
  GL_BLEND_EQUATION_ALPHA = $883D;
  GL_MAX_VERTEX_ATTRIBS = $8869;
  GL_VERTEX_ATTRIB_ARRAY_NORMALIZED = $886A;
  GL_MAX_TEXTURE_IMAGE_UNITS = $8872;
  GL_FRAGMENT_SHADER = $8B30;
  GL_VERTEX_SHADER = $8B31;
  GL_MAX_FRAGMENT_UNIFORM_COMPONENTS = $8B49;
  GL_MAX_VERTEX_UNIFORM_COMPONENTS = $8B4A;
  GL_MAX_VARYING_FLOATS = $8B4B;
  GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS = $8B4C;
  GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS = $8B4D;
  GL_SHADER_TYPE = $8B4F;
  GL_FLOAT_VEC2 = $8B50;
  GL_FLOAT_VEC3 = $8B51;
  GL_FLOAT_VEC4 = $8B52;
  GL_INT_VEC2 = $8B53;
  GL_INT_VEC3 = $8B54;
  GL_INT_VEC4 = $8B55;
  GL_BOOL = $8B56;
  GL_BOOL_VEC2 = $8B57;
  GL_BOOL_VEC3 = $8B58;
  GL_BOOL_VEC4 = $8B59;
  GL_FLOAT_MAT2 = $8B5A;
  GL_FLOAT_MAT3 = $8B5B;
  GL_FLOAT_MAT4 = $8B5C;
  GL_SAMPLER_1D = $8B5D;
  GL_SAMPLER_2D = $8B5E;
  GL_SAMPLER_3D = $8B5F;
  GL_SAMPLER_CUBE = $8B60;
  GL_SAMPLER_1D_SHADOW = $8B61;
  GL_SAMPLER_2D_SHADOW = $8B62;
  GL_DELETE_STATUS = $8B80;
  GL_COMPILE_STATUS = $8B81;
  GL_LINK_STATUS = $8B82;
  GL_VALIDATE_STATUS = $8B83;
  GL_INFO_LOG_LENGTH = $8B84;
  GL_ATTACHED_SHADERS = $8B85;
  GL_ACTIVE_UNIFORMS = $8B86;
  GL_ACTIVE_UNIFORM_MAX_LENGTH = $8B87;
  GL_SHADER_SOURCE_LENGTH = $8B88;
  GL_ACTIVE_ATTRIBUTES = $8B89;
  GL_ACTIVE_ATTRIBUTE_MAX_LENGTH = $8B8A;
  GL_FRAGMENT_SHADER_DERIVATIVE_HINT = $8B8B;
  GL_SHADING_LANGUAGE_VERSION = $8B8C;
  GL_CURRENT_PROGRAM = $8B8D;
  GL_POINT_SPRITE_COORD_ORIGIN = $8CA0;
  GL_LOWER_LEFT = $8CA1;
  GL_UPPER_LEFT = $8CA2;
  GL_STENCIL_BACK_REF = $8CA3;
  GL_STENCIL_BACK_VALUE_MASK = $8CA4;
  GL_STENCIL_BACK_WRITEMASK = $8CA5;
  GL_PIXEL_PACK_BUFFER = $88EB;
  GL_PIXEL_UNPACK_BUFFER = $88EC;
  GL_PIXEL_PACK_BUFFER_BINDING = $88ED;
  GL_PIXEL_UNPACK_BUFFER_BINDING = $88EF;
  GL_FLOAT_MAT2x3 = $8B65;
  GL_FLOAT_MAT2x4 = $8B66;
  GL_FLOAT_MAT3x2 = $8B67;
  GL_FLOAT_MAT3x4 = $8B68;
  GL_FLOAT_MAT4x2 = $8B69;
  GL_FLOAT_MAT4x3 = $8B6A;
  GL_SRGB = $8C40;
  GL_SRGB8 = $8C41;
  GL_SRGB_ALPHA = $8C42;
  GL_SRGB8_ALPHA8 = $8C43;
  GL_COMPRESSED_SRGB = $8C48;
  GL_COMPRESSED_SRGB_ALPHA = $8C49;
  GL_COMPARE_REF_TO_TEXTURE = $884E;
  GL_CLIP_DISTANCE0 = $3000;
  GL_CLIP_DISTANCE1 = $3001;
  GL_CLIP_DISTANCE2 = $3002;
  GL_CLIP_DISTANCE3 = $3003;
  GL_CLIP_DISTANCE4 = $3004;
  GL_CLIP_DISTANCE5 = $3005;
  GL_CLIP_DISTANCE6 = $3006;
  GL_CLIP_DISTANCE7 = $3007;
  GL_MAX_CLIP_DISTANCES = $0D32;
  GL_MAJOR_VERSION = $821B;
  GL_MINOR_VERSION = $821C;
  GL_NUM_EXTENSIONS = $821D;
  GL_CONTEXT_FLAGS = $821E;
  GL_COMPRESSED_RED = $8225;
  GL_COMPRESSED_RG = $8226;
  GL_CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT = $00000001;
  GL_RGBA32F = $8814;
  GL_RGB32F = $8815;
  GL_RGBA16F = $881A;
  GL_RGB16F = $881B;
  GL_VERTEX_ATTRIB_ARRAY_INTEGER = $88FD;
  GL_MAX_ARRAY_TEXTURE_LAYERS = $88FF;
  GL_MIN_PROGRAM_TEXEL_OFFSET = $8904;
  GL_MAX_PROGRAM_TEXEL_OFFSET = $8905;
  GL_CLAMP_READ_COLOR = $891C;
  GL_FIXED_ONLY = $891D;
  GL_MAX_VARYING_COMPONENTS = $8B4B;
  GL_TEXTURE_1D_ARRAY = $8C18;
  GL_PROXY_TEXTURE_1D_ARRAY = $8C19;
  GL_TEXTURE_2D_ARRAY = $8C1A;
  GL_PROXY_TEXTURE_2D_ARRAY = $8C1B;
  GL_TEXTURE_BINDING_1D_ARRAY = $8C1C;
  GL_TEXTURE_BINDING_2D_ARRAY = $8C1D;
  GL_R11F_G11F_B10F = $8C3A;
  GL_UNSIGNED_INT_10F_11F_11F_REV = $8C3B;
  GL_RGB9_E5 = $8C3D;
  GL_UNSIGNED_INT_5_9_9_9_REV = $8C3E;
  GL_TEXTURE_SHARED_SIZE = $8C3F;
  GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH = $8C76;
  GL_TRANSFORM_FEEDBACK_BUFFER_MODE = $8C7F;
  GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS = $8C80;
  GL_TRANSFORM_FEEDBACK_VARYINGS = $8C83;
  GL_TRANSFORM_FEEDBACK_BUFFER_START = $8C84;
  GL_TRANSFORM_FEEDBACK_BUFFER_SIZE = $8C85;
  GL_PRIMITIVES_GENERATED = $8C87;
  GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN = $8C88;
  GL_RASTERIZER_DISCARD = $8C89;
  GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS = $8C8A;
  GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS = $8C8B;
  GL_INTERLEAVED_ATTRIBS = $8C8C;
  GL_SEPARATE_ATTRIBS = $8C8D;
  GL_TRANSFORM_FEEDBACK_BUFFER = $8C8E;
  GL_TRANSFORM_FEEDBACK_BUFFER_BINDING = $8C8F;
  GL_RGBA32UI = $8D70;
  GL_RGB32UI = $8D71;
  GL_RGBA16UI = $8D76;
  GL_RGB16UI = $8D77;
  GL_RGBA8UI = $8D7C;
  GL_RGB8UI = $8D7D;
  GL_RGBA32I = $8D82;
  GL_RGB32I = $8D83;
  GL_RGBA16I = $8D88;
  GL_RGB16I = $8D89;
  GL_RGBA8I = $8D8E;
  GL_RGB8I = $8D8F;
  GL_RED_INTEGER = $8D94;
  GL_GREEN_INTEGER = $8D95;
  GL_BLUE_INTEGER = $8D96;
  GL_RGB_INTEGER = $8D98;
  GL_RGBA_INTEGER = $8D99;
  GL_BGR_INTEGER = $8D9A;
  GL_BGRA_INTEGER = $8D9B;
  GL_SAMPLER_1D_ARRAY = $8DC0;
  GL_SAMPLER_2D_ARRAY = $8DC1;
  GL_SAMPLER_1D_ARRAY_SHADOW = $8DC3;
  GL_SAMPLER_2D_ARRAY_SHADOW = $8DC4;
  GL_SAMPLER_CUBE_SHADOW = $8DC5;
  GL_UNSIGNED_INT_VEC2 = $8DC6;
  GL_UNSIGNED_INT_VEC3 = $8DC7;
  GL_UNSIGNED_INT_VEC4 = $8DC8;
  GL_INT_SAMPLER_1D = $8DC9;
  GL_INT_SAMPLER_2D = $8DCA;
  GL_INT_SAMPLER_3D = $8DCB;
  GL_INT_SAMPLER_CUBE = $8DCC;
  GL_INT_SAMPLER_1D_ARRAY = $8DCE;
  GL_INT_SAMPLER_2D_ARRAY = $8DCF;
  GL_UNSIGNED_INT_SAMPLER_1D = $8DD1;
  GL_UNSIGNED_INT_SAMPLER_2D = $8DD2;
  GL_UNSIGNED_INT_SAMPLER_3D = $8DD3;
  GL_UNSIGNED_INT_SAMPLER_CUBE = $8DD4;
  GL_UNSIGNED_INT_SAMPLER_1D_ARRAY = $8DD6;
  GL_UNSIGNED_INT_SAMPLER_2D_ARRAY = $8DD7;
  GL_QUERY_WAIT = $8E13;
  GL_QUERY_NO_WAIT = $8E14;
  GL_QUERY_BY_REGION_WAIT = $8E15;
  GL_QUERY_BY_REGION_NO_WAIT = $8E16;
  GL_BUFFER_ACCESS_FLAGS = $911F;
  GL_BUFFER_MAP_LENGTH = $9120;
  GL_BUFFER_MAP_OFFSET = $9121;
  GL_DEPTH_COMPONENT32F = $8CAC;
  GL_DEPTH32F_STENCIL8 = $8CAD;
  GL_FLOAT_32_UNSIGNED_INT_24_8_REV = $8DAD;
  GL_INVALID_FRAMEBUFFER_OPERATION = $0506;
  GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING = $8210;
  GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE = $8211;
  GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE = $8212;
  GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE = $8213;
  GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE = $8214;
  GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE = $8215;
  GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE = $8216;
  GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE = $8217;
  GL_FRAMEBUFFER_DEFAULT = $8218;
  GL_FRAMEBUFFER_UNDEFINED = $8219;
  GL_DEPTH_STENCIL_ATTACHMENT = $821A;
  GL_MAX_RENDERBUFFER_SIZE = $84E8;
  GL_DEPTH_STENCIL = $84F9;
  GL_UNSIGNED_INT_24_8 = $84FA;
  GL_DEPTH24_STENCIL8 = $88F0;
  GL_TEXTURE_STENCIL_SIZE = $88F1;
  GL_TEXTURE_RED_TYPE = $8C10;
  GL_TEXTURE_GREEN_TYPE = $8C11;
  GL_TEXTURE_BLUE_TYPE = $8C12;
  GL_TEXTURE_ALPHA_TYPE = $8C13;
  GL_TEXTURE_DEPTH_TYPE = $8C16;
  GL_UNSIGNED_NORMALIZED = $8C17;
  GL_FRAMEBUFFER_BINDING = $8CA6;
  GL_DRAW_FRAMEBUFFER_BINDING = $8CA6;
  GL_RENDERBUFFER_BINDING = $8CA7;
  GL_READ_FRAMEBUFFER = $8CA8;
  GL_DRAW_FRAMEBUFFER = $8CA9;
  GL_READ_FRAMEBUFFER_BINDING = $8CAA;
  GL_RENDERBUFFER_SAMPLES = $8CAB;
  GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE = $8CD0;
  GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME = $8CD1;
  GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL = $8CD2;
  GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE = $8CD3;
  GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER = $8CD4;
  GL_FRAMEBUFFER_COMPLETE = $8CD5;
  GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT = $8CD6;
  GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT = $8CD7;
  GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER = $8CDB;
  GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER = $8CDC;
  GL_FRAMEBUFFER_UNSUPPORTED = $8CDD;
  GL_MAX_COLOR_ATTACHMENTS = $8CDF;
  GL_COLOR_ATTACHMENT0 = $8CE0;
  GL_COLOR_ATTACHMENT1 = $8CE1;
  GL_COLOR_ATTACHMENT2 = $8CE2;
  GL_COLOR_ATTACHMENT3 = $8CE3;
  GL_COLOR_ATTACHMENT4 = $8CE4;
  GL_COLOR_ATTACHMENT5 = $8CE5;
  GL_COLOR_ATTACHMENT6 = $8CE6;
  GL_COLOR_ATTACHMENT7 = $8CE7;
  GL_COLOR_ATTACHMENT8 = $8CE8;
  GL_COLOR_ATTACHMENT9 = $8CE9;
  GL_COLOR_ATTACHMENT10 = $8CEA;
  GL_COLOR_ATTACHMENT11 = $8CEB;
  GL_COLOR_ATTACHMENT12 = $8CEC;
  GL_COLOR_ATTACHMENT13 = $8CED;
  GL_COLOR_ATTACHMENT14 = $8CEE;
  GL_COLOR_ATTACHMENT15 = $8CEF;
  GL_COLOR_ATTACHMENT16 = $8CF0;
  GL_COLOR_ATTACHMENT17 = $8CF1;
  GL_COLOR_ATTACHMENT18 = $8CF2;
  GL_COLOR_ATTACHMENT19 = $8CF3;
  GL_COLOR_ATTACHMENT20 = $8CF4;
  GL_COLOR_ATTACHMENT21 = $8CF5;
  GL_COLOR_ATTACHMENT22 = $8CF6;
  GL_COLOR_ATTACHMENT23 = $8CF7;
  GL_COLOR_ATTACHMENT24 = $8CF8;
  GL_COLOR_ATTACHMENT25 = $8CF9;
  GL_COLOR_ATTACHMENT26 = $8CFA;
  GL_COLOR_ATTACHMENT27 = $8CFB;
  GL_COLOR_ATTACHMENT28 = $8CFC;
  GL_COLOR_ATTACHMENT29 = $8CFD;
  GL_COLOR_ATTACHMENT30 = $8CFE;
  GL_COLOR_ATTACHMENT31 = $8CFF;
  GL_DEPTH_ATTACHMENT = $8D00;
  GL_STENCIL_ATTACHMENT = $8D20;
  GL_FRAMEBUFFER = $8D40;
  GL_RENDERBUFFER = $8D41;
  GL_RENDERBUFFER_WIDTH = $8D42;
  GL_RENDERBUFFER_HEIGHT = $8D43;
  GL_RENDERBUFFER_INTERNAL_FORMAT = $8D44;
  GL_STENCIL_INDEX1 = $8D46;
  GL_STENCIL_INDEX4 = $8D47;
  GL_STENCIL_INDEX8 = $8D48;
  GL_STENCIL_INDEX16 = $8D49;
  GL_RENDERBUFFER_RED_SIZE = $8D50;
  GL_RENDERBUFFER_GREEN_SIZE = $8D51;
  GL_RENDERBUFFER_BLUE_SIZE = $8D52;
  GL_RENDERBUFFER_ALPHA_SIZE = $8D53;
  GL_RENDERBUFFER_DEPTH_SIZE = $8D54;
  GL_RENDERBUFFER_STENCIL_SIZE = $8D55;
  GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE = $8D56;
  GL_MAX_SAMPLES = $8D57;
  GL_FRAMEBUFFER_SRGB = $8DB9;
  GL_HALF_FLOAT = $140B;
  GL_MAP_READ_BIT = $0001;
  GL_MAP_WRITE_BIT = $0002;
  GL_MAP_INVALIDATE_RANGE_BIT = $0004;
  GL_MAP_INVALIDATE_BUFFER_BIT = $0008;
  GL_MAP_FLUSH_EXPLICIT_BIT = $0010;
  GL_MAP_UNSYNCHRONIZED_BIT = $0020;
  GL_COMPRESSED_RED_RGTC1 = $8DBB;
  GL_COMPRESSED_SIGNED_RED_RGTC1 = $8DBC;
  GL_COMPRESSED_RG_RGTC2 = $8DBD;
  GL_COMPRESSED_SIGNED_RG_RGTC2 = $8DBE;
  GL_RG = $8227;
  GL_RG_INTEGER = $8228;
  GL_R8 = $8229;
  GL_R16 = $822A;
  GL_RG8 = $822B;
  GL_RG16 = $822C;
  GL_R16F = $822D;
  GL_R32F = $822E;
  GL_RG16F = $822F;
  GL_RG32F = $8230;
  GL_R8I = $8231;
  GL_R8UI = $8232;
  GL_R16I = $8233;
  GL_R16UI = $8234;
  GL_R32I = $8235;
  GL_R32UI = $8236;
  GL_RG8I = $8237;
  GL_RG8UI = $8238;
  GL_RG16I = $8239;
  GL_RG16UI = $823A;
  GL_RG32I = $823B;
  GL_RG32UI = $823C;
  GL_VERTEX_ARRAY_BINDING = $85B5;
  GL_SAMPLER_2D_RECT = $8B63;
  GL_SAMPLER_2D_RECT_SHADOW = $8B64;
  GL_SAMPLER_BUFFER = $8DC2;
  GL_INT_SAMPLER_2D_RECT = $8DCD;
  GL_INT_SAMPLER_BUFFER = $8DD0;
  GL_UNSIGNED_INT_SAMPLER_2D_RECT = $8DD5;
  GL_UNSIGNED_INT_SAMPLER_BUFFER = $8DD8;
  GL_TEXTURE_BUFFER = $8C2A;
  GL_MAX_TEXTURE_BUFFER_SIZE = $8C2B;
  GL_TEXTURE_BINDING_BUFFER = $8C2C;
  GL_TEXTURE_BUFFER_DATA_STORE_BINDING = $8C2D;
  GL_TEXTURE_RECTANGLE = $84F5;
  GL_TEXTURE_BINDING_RECTANGLE = $84F6;
  GL_PROXY_TEXTURE_RECTANGLE = $84F7;
  GL_MAX_RECTANGLE_TEXTURE_SIZE = $84F8;
  GL_R8_SNORM = $8F94;
  GL_RG8_SNORM = $8F95;
  GL_RGB8_SNORM = $8F96;
  GL_RGBA8_SNORM = $8F97;
  GL_R16_SNORM = $8F98;
  GL_RG16_SNORM = $8F99;
  GL_RGB16_SNORM = $8F9A;
  GL_RGBA16_SNORM = $8F9B;
  GL_SIGNED_NORMALIZED = $8F9C;
  GL_PRIMITIVE_RESTART = $8F9D;
  GL_PRIMITIVE_RESTART_INDEX = $8F9E;
  GL_COPY_READ_BUFFER = $8F36;
  GL_COPY_WRITE_BUFFER = $8F37;
  GL_UNIFORM_BUFFER = $8A11;
  GL_UNIFORM_BUFFER_BINDING = $8A28;
  GL_UNIFORM_BUFFER_START = $8A29;
  GL_UNIFORM_BUFFER_SIZE = $8A2A;
  GL_MAX_VERTEX_UNIFORM_BLOCKS = $8A2B;
  GL_MAX_GEOMETRY_UNIFORM_BLOCKS = $8A2C;
  GL_MAX_FRAGMENT_UNIFORM_BLOCKS = $8A2D;
  GL_MAX_COMBINED_UNIFORM_BLOCKS = $8A2E;
  GL_MAX_UNIFORM_BUFFER_BINDINGS = $8A2F;
  GL_MAX_UNIFORM_BLOCK_SIZE = $8A30;
  GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS = $8A31;
  GL_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS = $8A32;
  GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS = $8A33;
  GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT = $8A34;
  GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH = $8A35;
  GL_ACTIVE_UNIFORM_BLOCKS = $8A36;
  GL_UNIFORM_TYPE = $8A37;
  GL_UNIFORM_SIZE = $8A38;
  GL_UNIFORM_NAME_LENGTH = $8A39;
  GL_UNIFORM_BLOCK_INDEX = $8A3A;
  GL_UNIFORM_OFFSET = $8A3B;
  GL_UNIFORM_ARRAY_STRIDE = $8A3C;
  GL_UNIFORM_MATRIX_STRIDE = $8A3D;
  GL_UNIFORM_IS_ROW_MAJOR = $8A3E;
  GL_UNIFORM_BLOCK_BINDING = $8A3F;
  GL_UNIFORM_BLOCK_DATA_SIZE = $8A40;
  GL_UNIFORM_BLOCK_NAME_LENGTH = $8A41;
  GL_UNIFORM_BLOCK_ACTIVE_UNIFORMS = $8A42;
  GL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES = $8A43;
  GL_UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER = $8A44;
  GL_UNIFORM_BLOCK_REFERENCED_BY_GEOMETRY_SHADER = $8A45;
  GL_UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER = $8A46;
  GL_CONTEXT_CORE_PROFILE_BIT = $00000001;
  GL_CONTEXT_COMPATIBILITY_PROFILE_BIT = $00000002;
  GL_LINES_ADJACENCY = $000A;
  GL_LINE_STRIP_ADJACENCY = $000B;
  GL_TRIANGLES_ADJACENCY = $000C;
  GL_TRIANGLE_STRIP_ADJACENCY = $000D;
  GL_PROGRAM_POINT_SIZE = $8642;
  GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS = $8C29;
  GL_FRAMEBUFFER_ATTACHMENT_LAYERED = $8DA7;
  GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS = $8DA8;
  GL_GEOMETRY_SHADER = $8DD9;
  GL_GEOMETRY_VERTICES_OUT = $8916;
  GL_GEOMETRY_INPUT_TYPE = $8917;
  GL_GEOMETRY_OUTPUT_TYPE = $8918;
  GL_MAX_GEOMETRY_UNIFORM_COMPONENTS = $8DDF;
  GL_MAX_GEOMETRY_OUTPUT_VERTICES = $8DE0;
  GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS = $8DE1;
  GL_MAX_VERTEX_OUTPUT_COMPONENTS = $9122;
  GL_MAX_GEOMETRY_INPUT_COMPONENTS = $9123;
  GL_MAX_GEOMETRY_OUTPUT_COMPONENTS = $9124;
  GL_MAX_FRAGMENT_INPUT_COMPONENTS = $9125;
  GL_CONTEXT_PROFILE_MASK = $9126;
  GL_DEPTH_CLAMP = $864F;
  GL_QUADS_FOLLOW_PROVOKING_VERTEX_CONVENTION = $8E4C;
  GL_FIRST_VERTEX_CONVENTION = $8E4D;
  GL_LAST_VERTEX_CONVENTION = $8E4E;
  GL_PROVOKING_VERTEX = $8E4F;
  GL_TEXTURE_CUBE_MAP_SEAMLESS = $884F;
  GL_MAX_SERVER_WAIT_TIMEOUT = $9111;
  GL_OBJECT_TYPE = $9112;
  GL_SYNC_CONDITION = $9113;
  GL_SYNC_STATUS = $9114;
  GL_SYNC_FLAGS = $9115;
  GL_SYNC_FENCE = $9116;
  GL_SYNC_GPU_COMMANDS_COMPLETE = $9117;
  GL_UNSIGNALED = $9118;
  GL_SIGNALED = $9119;
  GL_ALREADY_SIGNALED = $911A;
  GL_TIMEOUT_EXPIRED = $911B;
  GL_CONDITION_SATISFIED = $911C;
  GL_WAIT_FAILED = $911D;
  GL_SYNC_FLUSH_COMMANDS_BIT = $00000001;
  GL_SAMPLE_POSITION = $8E50;
  GL_SAMPLE_MASK = $8E51;
  GL_SAMPLE_MASK_VALUE = $8E52;
  GL_MAX_SAMPLE_MASK_WORDS = $8E59;
  GL_TEXTURE_2D_MULTISAMPLE = $9100;
  GL_PROXY_TEXTURE_2D_MULTISAMPLE = $9101;
  GL_TEXTURE_2D_MULTISAMPLE_ARRAY = $9102;
  GL_PROXY_TEXTURE_2D_MULTISAMPLE_ARRAY = $9103;
  GL_TEXTURE_BINDING_2D_MULTISAMPLE = $9104;
  GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY = $9105;
  GL_TEXTURE_SAMPLES = $9106;
  GL_TEXTURE_FIXED_SAMPLE_LOCATIONS = $9107;
  GL_SAMPLER_2D_MULTISAMPLE = $9108;
  GL_INT_SAMPLER_2D_MULTISAMPLE = $9109;
  GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE = $910A;
  GL_SAMPLER_2D_MULTISAMPLE_ARRAY = $910B;
  GL_INT_SAMPLER_2D_MULTISAMPLE_ARRAY = $910C;
  GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY = $910D;
  GL_MAX_COLOR_TEXTURE_SAMPLES = $910E;
  GL_MAX_DEPTH_TEXTURE_SAMPLES = $910F;
  GL_MAX_INTEGER_SAMPLES = $9110;
  GL_VERTEX_ATTRIB_ARRAY_DIVISOR = $88FE;
  GL_SRC1_COLOR = $88F9;
  GL_ONE_MINUS_SRC1_COLOR = $88FA;
  GL_ONE_MINUS_SRC1_ALPHA = $88FB;
  GL_MAX_DUAL_SOURCE_DRAW_BUFFERS = $88FC;
  GL_ANY_SAMPLES_PASSED = $8C2F;
  GL_SAMPLER_BINDING = $8919;
  GL_RGB10_A2UI = $906F;
  GL_TEXTURE_SWIZZLE_R = $8E42;
  GL_TEXTURE_SWIZZLE_G = $8E43;
  GL_TEXTURE_SWIZZLE_B = $8E44;
  GL_TEXTURE_SWIZZLE_A = $8E45;
  GL_TEXTURE_SWIZZLE_RGBA = $8E46;
  GL_TIME_ELAPSED = $88BF;
  GL_TIMESTAMP = $8E28;
  GL_INT_2_10_10_10_REV = $8D9F;

(* Functions *)
var
  GLAD_GL_VERSION_1_0: Boolean;
  GLAD_GL_VERSION_1_1: Boolean;
  GLAD_GL_VERSION_1_2: Boolean;
  GLAD_GL_VERSION_1_3: Boolean;
  GLAD_GL_VERSION_1_4: Boolean;
  GLAD_GL_VERSION_1_5: Boolean;
  GLAD_GL_VERSION_2_0: Boolean;
  GLAD_GL_VERSION_2_1: Boolean;
  GLAD_GL_VERSION_3_0: Boolean;
  GLAD_GL_VERSION_3_1: Boolean;
  GLAD_GL_VERSION_3_2: Boolean;
  GLAD_GL_VERSION_3_3: Boolean;

var
  glCullFace: procedure (mode: GLenum); apicall;
  glFrontFace: procedure (mode: GLenum); apicall;
  glHint: procedure (target: GLenum; mode: GLenum); apicall;
  glLineWidth: procedure (width: GLfloat); apicall;
  glPointSize: procedure (size: GLfloat); apicall;
  glPolygonMode: procedure (face: GLenum; mode: GLenum); apicall;
  glScissor: procedure (x: GLint; y: GLint; width: GLsizei; height: GLsizei); apicall;
  glTexParameterf: procedure (target: GLenum; pname: GLenum; param: GLfloat); apicall;
  glTexParameterfv: procedure (target: GLenum; pname: GLenum; params: PGLfloat); apicall;
  glTexParameteri: procedure (target: GLenum; pname: GLenum; param: GLint); apicall;
  glTexParameteriv: procedure (target: GLenum; pname: GLenum; params: PGLint); apicall;
  glTexImage1D: procedure (target: GLenum; level: GLint; internalformat: GLint; width: GLsizei; border: GLint; format: GLenum; type_: GLenum; pixels: Pointer); apicall;
  glTexImage2D: procedure (target: GLenum; level: GLint; internalformat: GLint; width: GLsizei; height: GLsizei; border: GLint; format: GLenum; type_: GLenum; pixels: Pointer); apicall;
  glDrawBuffer: procedure (buf: GLenum); apicall;
  glClear: procedure (mask: GLbitfield); apicall;
  glClearColor: procedure (red: GLfloat; green: GLfloat; blue: GLfloat; alpha: GLfloat); apicall;
  glClearStencil: procedure (s: GLint); apicall;
  glClearDepth: procedure (depth: GLdouble); apicall;
  glStencilMask: procedure (mask: GLuint); apicall;
  glColorMask: procedure (red: GLboolean; green: GLboolean; blue: GLboolean; alpha: GLboolean); apicall;
  glDepthMask: procedure (flag: GLboolean); apicall;
  glDisable: procedure (cap: GLenum); apicall;
  glEnable: procedure (cap: GLenum); apicall;
  glFinish: procedure (); apicall;
  glFlush: procedure (); apicall;
  glBlendFunc: procedure (sfactor: GLenum; dfactor: GLenum); apicall;
  glLogicOp: procedure (opcode: GLenum); apicall;
  glStencilFunc: procedure (func: GLenum; ref: GLint; mask: GLuint); apicall;
  glStencilOp: procedure (fail: GLenum; zfail: GLenum; zpass: GLenum); apicall;
  glDepthFunc: procedure (func: GLenum); apicall;
  glPixelStoref: procedure (pname: GLenum; param: GLfloat); apicall;
  glPixelStorei: procedure (pname: GLenum; param: GLint); apicall;
  glReadBuffer: procedure (src: GLenum); apicall;
  glReadPixels: procedure (x: GLint; y: GLint; width: GLsizei; height: GLsizei; format: GLenum; type_: GLenum; pixels: Pointer); apicall;
  glGetBooleanv: procedure (pname: GLenum; data: PGLboolean); apicall;
  glGetDoublev: procedure (pname: GLenum; data: PGLdouble); apicall;
  glGetError: function (): GLenum; apicall;
  glGetFloatv: procedure (pname: GLenum; data: PGLfloat); apicall;
  glGetIntegerv: procedure (pname: GLenum; data: PGLint); apicall;
  glGetString: function (name: GLenum): PGLubyte; apicall;
  glGetTexImage: procedure (target: GLenum; level: GLint; format: GLenum; type_: GLenum; pixels: Pointer); apicall;
  glGetTexParameterfv: procedure (target: GLenum; pname: GLenum; params: PGLfloat); apicall;
  glGetTexParameteriv: procedure (target: GLenum; pname: GLenum; params: PGLint); apicall;
  glGetTexLevelParameterfv: procedure (target: GLenum; level: GLint; pname: GLenum; params: PGLfloat); apicall;
  glGetTexLevelParameteriv: procedure (target: GLenum; level: GLint; pname: GLenum; params: PGLint); apicall;
  glIsEnabled: function (cap: GLenum): GLboolean; apicall;
  glDepthRange: procedure (n: GLdouble; f: GLdouble); apicall;
  glViewport: procedure (x: GLint; y: GLint; width: GLsizei; height: GLsizei); apicall;
  glDrawArrays: procedure (mode: GLenum; first: GLint; count: GLsizei); apicall;
  glDrawElements: procedure (mode: GLenum; count: GLsizei; type_: GLenum; indices: Pointer); apicall;
  glPolygonOffset: procedure (factor: GLfloat; units: GLfloat); apicall;
  glCopyTexImage1D: procedure (target: GLenum; level: GLint; internalformat: GLenum; x: GLint; y: GLint; width: GLsizei; border: GLint); apicall;
  glCopyTexImage2D: procedure (target: GLenum; level: GLint; internalformat: GLenum; x: GLint; y: GLint; width: GLsizei; height: GLsizei; border: GLint); apicall;
  glCopyTexSubImage1D: procedure (target: GLenum; level: GLint; xoffset: GLint; x: GLint; y: GLint; width: GLsizei); apicall;
  glCopyTexSubImage2D: procedure (target: GLenum; level: GLint; xoffset: GLint; yoffset: GLint; x: GLint; y: GLint; width: GLsizei; height: GLsizei); apicall;
  glTexSubImage1D: procedure (target: GLenum; level: GLint; xoffset: GLint; width: GLsizei; format: GLenum; type_: GLenum; pixels: Pointer); apicall;
  glTexSubImage2D: procedure (target: GLenum; level: GLint; xoffset: GLint; yoffset: GLint; width: GLsizei; height: GLsizei; format: GLenum; type_: GLenum; pixels: Pointer); apicall;
  glBindTexture: procedure (target: GLenum; texture: GLuint); apicall;
  glDeleteTextures: procedure (n: GLsizei; textures: PGLuint); apicall;
  glGenTextures: procedure (n: GLsizei; textures: PGLuint); apicall;
  glIsTexture: function (texture: GLuint): GLboolean; apicall;
  glDrawRangeElements: procedure (mode: GLenum; start: GLuint; end_: GLuint; count: GLsizei; type_: GLenum; indices: Pointer); apicall;
  glTexImage3D: procedure (target: GLenum; level: GLint; internalformat: GLint; width: GLsizei; height: GLsizei; depth: GLsizei; border: GLint; format: GLenum; type_: GLenum; pixels: Pointer); apicall;
  glTexSubImage3D: procedure (target: GLenum; level: GLint; xoffset: GLint; yoffset: GLint; zoffset: GLint; width: GLsizei; height: GLsizei; depth: GLsizei; format: GLenum; type_: GLenum; pixels: Pointer); apicall;
  glCopyTexSubImage3D: procedure (target: GLenum; level: GLint; xoffset: GLint; yoffset: GLint; zoffset: GLint; x: GLint; y: GLint; width: GLsizei; height: GLsizei); apicall;
  glActiveTexture: procedure (texture: GLenum); apicall;
  glSampleCoverage: procedure (value: GLfloat; invert: GLboolean); apicall;
  glCompressedTexImage3D: procedure (target: GLenum; level: GLint; internalformat: GLenum; width: GLsizei; height: GLsizei; depth: GLsizei; border: GLint; imageSize: GLsizei; data: Pointer); apicall;
  glCompressedTexImage2D: procedure (target: GLenum; level: GLint; internalformat: GLenum; width: GLsizei; height: GLsizei; border: GLint; imageSize: GLsizei; data: Pointer); apicall;
  glCompressedTexImage1D: procedure (target: GLenum; level: GLint; internalformat: GLenum; width: GLsizei; border: GLint; imageSize: GLsizei; data: Pointer); apicall;
  glCompressedTexSubImage3D: procedure (target: GLenum; level: GLint; xoffset: GLint; yoffset: GLint; zoffset: GLint; width: GLsizei; height: GLsizei; depth: GLsizei; format: GLenum; imageSize: GLsizei; data: Pointer); apicall;
  glCompressedTexSubImage2D: procedure (target: GLenum; level: GLint; xoffset: GLint; yoffset: GLint; width: GLsizei; height: GLsizei; format: GLenum; imageSize: GLsizei; data: Pointer); apicall;
  glCompressedTexSubImage1D: procedure (target: GLenum; level: GLint; xoffset: GLint; width: GLsizei; format: GLenum; imageSize: GLsizei; data: Pointer); apicall;
  glGetCompressedTexImage: procedure (target: GLenum; level: GLint; img: Pointer); apicall;
  glBlendFuncSeparate: procedure (sfactorRGB: GLenum; dfactorRGB: GLenum; sfactorAlpha: GLenum; dfactorAlpha: GLenum); apicall;
  glMultiDrawArrays: procedure (mode: GLenum; first: PGLint; count: PGLsizei; drawcount: GLsizei); apicall;
  glMultiDrawElements: procedure (mode: GLenum; count: PGLsizei; type_: GLenum; indices: PPointer; drawcount: GLsizei); apicall;
  glPointParameterf: procedure (pname: GLenum; param: GLfloat); apicall;
  glPointParameterfv: procedure (pname: GLenum; params: PGLfloat); apicall;
  glPointParameteri: procedure (pname: GLenum; param: GLint); apicall;
  glPointParameteriv: procedure (pname: GLenum; params: PGLint); apicall;
  glBlendColor: procedure (red: GLfloat; green: GLfloat; blue: GLfloat; alpha: GLfloat); apicall;
  glBlendEquation: procedure (mode: GLenum); apicall;
  glGenQueries: procedure (n: GLsizei; ids: PGLuint); apicall;
  glDeleteQueries: procedure (n: GLsizei; ids: PGLuint); apicall;
  glIsQuery: function (id: GLuint): GLboolean; apicall;
  glBeginQuery: procedure (target: GLenum; id: GLuint); apicall;
  glEndQuery: procedure (target: GLenum); apicall;
  glGetQueryiv: procedure (target: GLenum; pname: GLenum; params: PGLint); apicall;
  glGetQueryObjectiv: procedure (id: GLuint; pname: GLenum; params: PGLint); apicall;
  glGetQueryObjectuiv: procedure (id: GLuint; pname: GLenum; params: PGLuint); apicall;
  glBindBuffer: procedure (target: GLenum; buffer: GLuint); apicall;
  glDeleteBuffers: procedure (n: GLsizei; buffers: PGLuint); apicall;
  glGenBuffers: procedure (n: GLsizei; buffers: PGLuint); apicall;
  glIsBuffer: function (buffer: GLuint): GLboolean; apicall;
  glBufferData: procedure (target: GLenum; size: GLsizeiptr; data: Pointer; usage: GLenum); apicall;
  glBufferSubData: procedure (target: GLenum; offset: GLintptr; size: GLsizeiptr; data: Pointer); apicall;
  glGetBufferSubData: procedure (target: GLenum; offset: GLintptr; size: GLsizeiptr; data: Pointer); apicall;
  glMapBuffer: function (target: GLenum; access: GLenum): Pointer; apicall;
  glUnmapBuffer: function (target: GLenum): GLboolean; apicall;
  glGetBufferParameteriv: procedure (target: GLenum; pname: GLenum; params: PGLint); apicall;
  glGetBufferPointerv: procedure (target: GLenum; pname: GLenum; params: PPointer); apicall;
  glBlendEquationSeparate: procedure (modeRGB: GLenum; modeAlpha: GLenum); apicall;
  glDrawBuffers: procedure (n: GLsizei; bufs: PGLenum); apicall;
  glStencilOpSeparate: procedure (face: GLenum; sfail: GLenum; dpfail: GLenum; dppass: GLenum); apicall;
  glStencilFuncSeparate: procedure (face: GLenum; func: GLenum; ref: GLint; mask: GLuint); apicall;
  glStencilMaskSeparate: procedure (face: GLenum; mask: GLuint); apicall;
  glAttachShader: procedure (program_: GLuint; shader: GLuint); apicall;
  glBindAttribLocation: procedure (program_: GLuint; index: GLuint; name: PGLchar); apicall;
  glCompileShader: procedure (shader: GLuint); apicall;
  glCreateProgram: function (): GLuint; apicall;
  glCreateShader: function (type_: GLenum): GLuint; apicall;
  glDeleteProgram: procedure (program_: GLuint); apicall;
  glDeleteShader: procedure (shader: GLuint); apicall;
  glDetachShader: procedure (program_: GLuint; shader: GLuint); apicall;
  glDisableVertexAttribArray: procedure (index: GLuint); apicall;
  glEnableVertexAttribArray: procedure (index: GLuint); apicall;
  glGetActiveAttrib: procedure (program_: GLuint; index: GLuint; bufSize: GLsizei; length: PGLsizei; size: PGLint; type_: PGLenum; name: PGLchar); apicall;
  glGetActiveUniform: procedure (program_: GLuint; index: GLuint; bufSize: GLsizei; length: PGLsizei; size: PGLint; type_: PGLenum; name: PGLchar); apicall;
  glGetAttachedShaders: procedure (program_: GLuint; maxCount: GLsizei; count: PGLsizei; shaders: PGLuint); apicall;
  glGetAttribLocation: function (program_: GLuint; name: PGLchar): GLint; apicall;
  glGetProgramiv: procedure (program_: GLuint; pname: GLenum; params: PGLint); apicall;
  glGetProgramInfoLog: procedure (program_: GLuint; bufSize: GLsizei; length: PGLsizei; infoLog: PGLchar); apicall;
  glGetShaderiv: procedure (shader: GLuint; pname: GLenum; params: PGLint); apicall;
  glGetShaderInfoLog: procedure (shader: GLuint; bufSize: GLsizei; length: PGLsizei; infoLog: PGLchar); apicall;
  glGetShaderSource: procedure (shader: GLuint; bufSize: GLsizei; length: PGLsizei; source: PGLchar); apicall;
  glGetUniformLocation: function (program_: GLuint; name: PGLchar): GLint; apicall;
  glGetUniformfv: procedure (program_: GLuint; location: GLint; params: PGLfloat); apicall;
  glGetUniformiv: procedure (program_: GLuint; location: GLint; params: PGLint); apicall;
  glGetVertexAttribdv: procedure (index: GLuint; pname: GLenum; params: PGLdouble); apicall;
  glGetVertexAttribfv: procedure (index: GLuint; pname: GLenum; params: PGLfloat); apicall;
  glGetVertexAttribiv: procedure (index: GLuint; pname: GLenum; params: PGLint); apicall;
  glGetVertexAttribPointerv: procedure (index: GLuint; pname: GLenum; pointer: PPointer); apicall;
  glIsProgram: function (program_: GLuint): GLboolean; apicall;
  glIsShader: function (shader: GLuint): GLboolean; apicall;
  glLinkProgram: procedure (program_: GLuint); apicall;
  glShaderSource: procedure (shader: GLuint; count: GLsizei; string_: PPGLchar; length: PGLint); apicall;
  glUseProgram: procedure (program_: GLuint); apicall;
  glUniform1f: procedure (location: GLint; v0: GLfloat); apicall;
  glUniform2f: procedure (location: GLint; v0: GLfloat; v1: GLfloat); apicall;
  glUniform3f: procedure (location: GLint; v0: GLfloat; v1: GLfloat; v2: GLfloat); apicall;
  glUniform4f: procedure (location: GLint; v0: GLfloat; v1: GLfloat; v2: GLfloat; v3: GLfloat); apicall;
  glUniform1i: procedure (location: GLint; v0: GLint); apicall;
  glUniform2i: procedure (location: GLint; v0: GLint; v1: GLint); apicall;
  glUniform3i: procedure (location: GLint; v0: GLint; v1: GLint; v2: GLint); apicall;
  glUniform4i: procedure (location: GLint; v0: GLint; v1: GLint; v2: GLint; v3: GLint); apicall;
  glUniform1fv: procedure (location: GLint; count: GLsizei; value: PGLfloat); apicall;
  glUniform2fv: procedure (location: GLint; count: GLsizei; value: PGLfloat); apicall;
  glUniform3fv: procedure (location: GLint; count: GLsizei; value: PGLfloat); apicall;
  glUniform4fv: procedure (location: GLint; count: GLsizei; value: PGLfloat); apicall;
  glUniform1iv: procedure (location: GLint; count: GLsizei; value: PGLint); apicall;
  glUniform2iv: procedure (location: GLint; count: GLsizei; value: PGLint); apicall;
  glUniform3iv: procedure (location: GLint; count: GLsizei; value: PGLint); apicall;
  glUniform4iv: procedure (location: GLint; count: GLsizei; value: PGLint); apicall;
  glUniformMatrix2fv: procedure (location: GLint; count: GLsizei; transpose: GLboolean; value: PGLfloat); apicall;
  glUniformMatrix3fv: procedure (location: GLint; count: GLsizei; transpose: GLboolean; value: PGLfloat); apicall;
  glUniformMatrix4fv: procedure (location: GLint; count: GLsizei; transpose: GLboolean; value: PGLfloat); apicall;
  glValidateProgram: procedure (program_: GLuint); apicall;
  glVertexAttrib1d: procedure (index: GLuint; x: GLdouble); apicall;
  glVertexAttrib1dv: procedure (index: GLuint; v: PGLdouble); apicall;
  glVertexAttrib1f: procedure (index: GLuint; x: GLfloat); apicall;
  glVertexAttrib1fv: procedure (index: GLuint; v: PGLfloat); apicall;
  glVertexAttrib1s: procedure (index: GLuint; x: GLshort); apicall;
  glVertexAttrib1sv: procedure (index: GLuint; v: PGLshort); apicall;
  glVertexAttrib2d: procedure (index: GLuint; x: GLdouble; y: GLdouble); apicall;
  glVertexAttrib2dv: procedure (index: GLuint; v: PGLdouble); apicall;
  glVertexAttrib2f: procedure (index: GLuint; x: GLfloat; y: GLfloat); apicall;
  glVertexAttrib2fv: procedure (index: GLuint; v: PGLfloat); apicall;
  glVertexAttrib2s: procedure (index: GLuint; x: GLshort; y: GLshort); apicall;
  glVertexAttrib2sv: procedure (index: GLuint; v: PGLshort); apicall;
  glVertexAttrib3d: procedure (index: GLuint; x: GLdouble; y: GLdouble; z: GLdouble); apicall;
  glVertexAttrib3dv: procedure (index: GLuint; v: PGLdouble); apicall;
  glVertexAttrib3f: procedure (index: GLuint; x: GLfloat; y: GLfloat; z: GLfloat); apicall;
  glVertexAttrib3fv: procedure (index: GLuint; v: PGLfloat); apicall;
  glVertexAttrib3s: procedure (index: GLuint; x: GLshort; y: GLshort; z: GLshort); apicall;
  glVertexAttrib3sv: procedure (index: GLuint; v: PGLshort); apicall;
  glVertexAttrib4Nbv: procedure (index: GLuint; v: PGLbyte); apicall;
  glVertexAttrib4Niv: procedure (index: GLuint; v: PGLint); apicall;
  glVertexAttrib4Nsv: procedure (index: GLuint; v: PGLshort); apicall;
  glVertexAttrib4Nub: procedure (index: GLuint; x: GLubyte; y: GLubyte; z: GLubyte; w: GLubyte); apicall;
  glVertexAttrib4Nubv: procedure (index: GLuint; v: PGLubyte); apicall;
  glVertexAttrib4Nuiv: procedure (index: GLuint; v: PGLuint); apicall;
  glVertexAttrib4Nusv: procedure (index: GLuint; v: PGLushort); apicall;
  glVertexAttrib4bv: procedure (index: GLuint; v: PGLbyte); apicall;
  glVertexAttrib4d: procedure (index: GLuint; x: GLdouble; y: GLdouble; z: GLdouble; w: GLdouble); apicall;
  glVertexAttrib4dv: procedure (index: GLuint; v: PGLdouble); apicall;
  glVertexAttrib4f: procedure (index: GLuint; x: GLfloat; y: GLfloat; z: GLfloat; w: GLfloat); apicall;
  glVertexAttrib4fv: procedure (index: GLuint; v: PGLfloat); apicall;
  glVertexAttrib4iv: procedure (index: GLuint; v: PGLint); apicall;
  glVertexAttrib4s: procedure (index: GLuint; x: GLshort; y: GLshort; z: GLshort; w: GLshort); apicall;
  glVertexAttrib4sv: procedure (index: GLuint; v: PGLshort); apicall;
  glVertexAttrib4ubv: procedure (index: GLuint; v: PGLubyte); apicall;
  glVertexAttrib4uiv: procedure (index: GLuint; v: PGLuint); apicall;
  glVertexAttrib4usv: procedure (index: GLuint; v: PGLushort); apicall;
  glVertexAttribPointer: procedure (index: GLuint; size: GLint; type_: GLenum; normalized: GLboolean; stride: GLsizei; pointer: Pointer); apicall;
  glUniformMatrix2x3fv: procedure (location: GLint; count: GLsizei; transpose: GLboolean; value: PGLfloat); apicall;
  glUniformMatrix3x2fv: procedure (location: GLint; count: GLsizei; transpose: GLboolean; value: PGLfloat); apicall;
  glUniformMatrix2x4fv: procedure (location: GLint; count: GLsizei; transpose: GLboolean; value: PGLfloat); apicall;
  glUniformMatrix4x2fv: procedure (location: GLint; count: GLsizei; transpose: GLboolean; value: PGLfloat); apicall;
  glUniformMatrix3x4fv: procedure (location: GLint; count: GLsizei; transpose: GLboolean; value: PGLfloat); apicall;
  glUniformMatrix4x3fv: procedure (location: GLint; count: GLsizei; transpose: GLboolean; value: PGLfloat); apicall;
  glColorMaski: procedure (index: GLuint; r: GLboolean; g: GLboolean; b: GLboolean; a: GLboolean); apicall;
  glGetBooleani_v: procedure (target: GLenum; index: GLuint; data: PGLboolean); apicall;
  glGetIntegeri_v: procedure (target: GLenum; index: GLuint; data: PGLint); apicall;
  glEnablei: procedure (target: GLenum; index: GLuint); apicall;
  glDisablei: procedure (target: GLenum; index: GLuint); apicall;
  glIsEnabledi: function (target: GLenum; index: GLuint): GLboolean; apicall;
  glBeginTransformFeedback: procedure (primitiveMode: GLenum); apicall;
  glEndTransformFeedback: procedure (); apicall;
  glBindBufferRange: procedure (target: GLenum; index: GLuint; buffer: GLuint; offset: GLintptr; size: GLsizeiptr); apicall;
  glBindBufferBase: procedure (target: GLenum; index: GLuint; buffer: GLuint); apicall;
  glTransformFeedbackVaryings: procedure (program_: GLuint; count: GLsizei; varyings: PPGLchar; bufferMode: GLenum); apicall;
  glGetTransformFeedbackVarying: procedure (program_: GLuint; index: GLuint; bufSize: GLsizei; length: PGLsizei; size: PGLsizei; type_: PGLenum; name: PGLchar); apicall;
  glClampColor: procedure (target: GLenum; clamp: GLenum); apicall;
  glBeginConditionalRender: procedure (id: GLuint; mode: GLenum); apicall;
  glEndConditionalRender: procedure (); apicall;
  glVertexAttribIPointer: procedure (index: GLuint; size: GLint; type_: GLenum; stride: GLsizei; pointer: Pointer); apicall;
  glGetVertexAttribIiv: procedure (index: GLuint; pname: GLenum; params: PGLint); apicall;
  glGetVertexAttribIuiv: procedure (index: GLuint; pname: GLenum; params: PGLuint); apicall;
  glVertexAttribI1i: procedure (index: GLuint; x: GLint); apicall;
  glVertexAttribI2i: procedure (index: GLuint; x: GLint; y: GLint); apicall;
  glVertexAttribI3i: procedure (index: GLuint; x: GLint; y: GLint; z: GLint); apicall;
  glVertexAttribI4i: procedure (index: GLuint; x: GLint; y: GLint; z: GLint; w: GLint); apicall;
  glVertexAttribI1ui: procedure (index: GLuint; x: GLuint); apicall;
  glVertexAttribI2ui: procedure (index: GLuint; x: GLuint; y: GLuint); apicall;
  glVertexAttribI3ui: procedure (index: GLuint; x: GLuint; y: GLuint; z: GLuint); apicall;
  glVertexAttribI4ui: procedure (index: GLuint; x: GLuint; y: GLuint; z: GLuint; w: GLuint); apicall;
  glVertexAttribI1iv: procedure (index: GLuint; v: PGLint); apicall;
  glVertexAttribI2iv: procedure (index: GLuint; v: PGLint); apicall;
  glVertexAttribI3iv: procedure (index: GLuint; v: PGLint); apicall;
  glVertexAttribI4iv: procedure (index: GLuint; v: PGLint); apicall;
  glVertexAttribI1uiv: procedure (index: GLuint; v: PGLuint); apicall;
  glVertexAttribI2uiv: procedure (index: GLuint; v: PGLuint); apicall;
  glVertexAttribI3uiv: procedure (index: GLuint; v: PGLuint); apicall;
  glVertexAttribI4uiv: procedure (index: GLuint; v: PGLuint); apicall;
  glVertexAttribI4bv: procedure (index: GLuint; v: PGLbyte); apicall;
  glVertexAttribI4sv: procedure (index: GLuint; v: PGLshort); apicall;
  glVertexAttribI4ubv: procedure (index: GLuint; v: PGLubyte); apicall;
  glVertexAttribI4usv: procedure (index: GLuint; v: PGLushort); apicall;
  glGetUniformuiv: procedure (program_: GLuint; location: GLint; params: PGLuint); apicall;
  glBindFragDataLocation: procedure (program_: GLuint; color: GLuint; name: PGLchar); apicall;
  glGetFragDataLocation: function (program_: GLuint; name: PGLchar): GLint; apicall;
  glUniform1ui: procedure (location: GLint; v0: GLuint); apicall;
  glUniform2ui: procedure (location: GLint; v0: GLuint; v1: GLuint); apicall;
  glUniform3ui: procedure (location: GLint; v0: GLuint; v1: GLuint; v2: GLuint); apicall;
  glUniform4ui: procedure (location: GLint; v0: GLuint; v1: GLuint; v2: GLuint; v3: GLuint); apicall;
  glUniform1uiv: procedure (location: GLint; count: GLsizei; value: PGLuint); apicall;
  glUniform2uiv: procedure (location: GLint; count: GLsizei; value: PGLuint); apicall;
  glUniform3uiv: procedure (location: GLint; count: GLsizei; value: PGLuint); apicall;
  glUniform4uiv: procedure (location: GLint; count: GLsizei; value: PGLuint); apicall;
  glTexParameterIiv: procedure (target: GLenum; pname: GLenum; params: PGLint); apicall;
  glTexParameterIuiv: procedure (target: GLenum; pname: GLenum; params: PGLuint); apicall;
  glGetTexParameterIiv: procedure (target: GLenum; pname: GLenum; params: PGLint); apicall;
  glGetTexParameterIuiv: procedure (target: GLenum; pname: GLenum; params: PGLuint); apicall;
  glClearBufferiv: procedure (buffer: GLenum; drawbuffer: GLint; value: PGLint); apicall;
  glClearBufferuiv: procedure (buffer: GLenum; drawbuffer: GLint; value: PGLuint); apicall;
  glClearBufferfv: procedure (buffer: GLenum; drawbuffer: GLint; value: PGLfloat); apicall;
  glClearBufferfi: procedure (buffer: GLenum; drawbuffer: GLint; depth: GLfloat; stencil: GLint); apicall;
  glGetStringi: function (name: GLenum; index: GLuint): PGLubyte; apicall;
  glIsRenderbuffer: function (renderbuffer: GLuint): GLboolean; apicall;
  glBindRenderbuffer: procedure (target: GLenum; renderbuffer: GLuint); apicall;
  glDeleteRenderbuffers: procedure (n: GLsizei; renderbuffers: PGLuint); apicall;
  glGenRenderbuffers: procedure (n: GLsizei; renderbuffers: PGLuint); apicall;
  glRenderbufferStorage: procedure (target: GLenum; internalformat: GLenum; width: GLsizei; height: GLsizei); apicall;
  glGetRenderbufferParameteriv: procedure (target: GLenum; pname: GLenum; params: PGLint); apicall;
  glIsFramebuffer: function (framebuffer: GLuint): GLboolean; apicall;
  glBindFramebuffer: procedure (target: GLenum; framebuffer: GLuint); apicall;
  glDeleteFramebuffers: procedure (n: GLsizei; framebuffers: PGLuint); apicall;
  glGenFramebuffers: procedure (n: GLsizei; framebuffers: PGLuint); apicall;
  glCheckFramebufferStatus: function (target: GLenum): GLenum; apicall;
  glFramebufferTexture1D: procedure (target: GLenum; attachment: GLenum; textarget: GLenum; texture: GLuint; level: GLint); apicall;
  glFramebufferTexture2D: procedure (target: GLenum; attachment: GLenum; textarget: GLenum; texture: GLuint; level: GLint); apicall;
  glFramebufferTexture3D: procedure (target: GLenum; attachment: GLenum; textarget: GLenum; texture: GLuint; level: GLint; zoffset: GLint); apicall;
  glFramebufferRenderbuffer: procedure (target: GLenum; attachment: GLenum; renderbuffertarget: GLenum; renderbuffer: GLuint); apicall;
  glGetFramebufferAttachmentParameteriv: procedure (target: GLenum; attachment: GLenum; pname: GLenum; params: PGLint); apicall;
  glGenerateMipmap: procedure (target: GLenum); apicall;
  glBlitFramebuffer: procedure (srcX0: GLint; srcY0: GLint; srcX1: GLint; srcY1: GLint; dstX0: GLint; dstY0: GLint; dstX1: GLint; dstY1: GLint; mask: GLbitfield; filter: GLenum); apicall;
  glRenderbufferStorageMultisample: procedure (target: GLenum; samples: GLsizei; internalformat: GLenum; width: GLsizei; height: GLsizei); apicall;
  glFramebufferTextureLayer: procedure (target: GLenum; attachment: GLenum; texture: GLuint; level: GLint; layer: GLint); apicall;
  glMapBufferRange: function (target: GLenum; offset: GLintptr; length: GLsizeiptr; access: GLbitfield): Pointer; apicall;
  glFlushMappedBufferRange: procedure (target: GLenum; offset: GLintptr; length: GLsizeiptr); apicall;
  glBindVertexArray: procedure (array_: GLuint); apicall;
  glDeleteVertexArrays: procedure (n: GLsizei; arrays: PGLuint); apicall;
  glGenVertexArrays: procedure (n: GLsizei; arrays: PGLuint); apicall;
  glIsVertexArray: function (array_: GLuint): GLboolean; apicall;
  glDrawArraysInstanced: procedure (mode: GLenum; first: GLint; count: GLsizei; instancecount: GLsizei); apicall;
  glDrawElementsInstanced: procedure (mode: GLenum; count: GLsizei; type_: GLenum; indices: Pointer; instancecount: GLsizei); apicall;
  glTexBuffer: procedure (target: GLenum; internalformat: GLenum; buffer: GLuint); apicall;
  glPrimitiveRestartIndex: procedure (index: GLuint); apicall;
  glCopyBufferSubData: procedure (readTarget: GLenum; writeTarget: GLenum; readOffset: GLintptr; writeOffset: GLintptr; size: GLsizeiptr); apicall;
  glGetUniformIndices: procedure (program_: GLuint; uniformCount: GLsizei; uniformNames: PPGLchar; uniformIndices: PGLuint); apicall;
  glGetActiveUniformsiv: procedure (program_: GLuint; uniformCount: GLsizei; uniformIndices: PGLuint; pname: GLenum; params: PGLint); apicall;
  glGetActiveUniformName: procedure (program_: GLuint; uniformIndex: GLuint; bufSize: GLsizei; length: PGLsizei; uniformName: PGLchar); apicall;
  glGetUniformBlockIndex: function (program_: GLuint; uniformBlockName: PGLchar): GLuint; apicall;
  glGetActiveUniformBlockiv: procedure (program_: GLuint; uniformBlockIndex: GLuint; pname: GLenum; params: PGLint); apicall;
  glGetActiveUniformBlockName: procedure (program_: GLuint; uniformBlockIndex: GLuint; bufSize: GLsizei; length: PGLsizei; uniformBlockName: PGLchar); apicall;
  glUniformBlockBinding: procedure (program_: GLuint; uniformBlockIndex: GLuint; uniformBlockBinding: GLuint); apicall;
  glDrawElementsBaseVertex: procedure (mode: GLenum; count: GLsizei; type_: GLenum; indices: Pointer; basevertex: GLint); apicall;
  glDrawRangeElementsBaseVertex: procedure (mode: GLenum; start: GLuint; end_: GLuint; count: GLsizei; type_: GLenum; indices: Pointer; basevertex: GLint); apicall;
  glDrawElementsInstancedBaseVertex: procedure (mode: GLenum; count: GLsizei; type_: GLenum; indices: Pointer; instancecount: GLsizei; basevertex: GLint); apicall;
  glMultiDrawElementsBaseVertex: procedure (mode: GLenum; count: PGLsizei; type_: GLenum; indices: PPointer; drawcount: GLsizei; basevertex: PGLint); apicall;
  glProvokingVertex: procedure (mode: GLenum); apicall;
  glFenceSync: function (condition: GLenum; flags: GLbitfield): GLsync; apicall;
  glIsSync: function (sync: GLsync): GLboolean; apicall;
  glDeleteSync: procedure (sync: GLsync); apicall;
  glClientWaitSync: function (sync: GLsync; flags: GLbitfield; timeout: GLuint64): GLenum; apicall;
  glWaitSync: procedure (sync: GLsync; flags: GLbitfield; timeout: GLuint64); apicall;
  glGetInteger64v: procedure (pname: GLenum; data: PGLint64); apicall;
  glGetSynciv: procedure (sync: GLsync; pname: GLenum; count: GLsizei; length: PGLsizei; values: PGLint); apicall;
  glGetInteger64i_v: procedure (target: GLenum; index: GLuint; data: PGLint64); apicall;
  glGetBufferParameteri64v: procedure (target: GLenum; pname: GLenum; params: PGLint64); apicall;
  glFramebufferTexture: procedure (target: GLenum; attachment: GLenum; texture: GLuint; level: GLint); apicall;
  glTexImage2DMultisample: procedure (target: GLenum; samples: GLsizei; internalformat: GLenum; width: GLsizei; height: GLsizei; fixedsamplelocations: GLboolean); apicall;
  glTexImage3DMultisample: procedure (target: GLenum; samples: GLsizei; internalformat: GLenum; width: GLsizei; height: GLsizei; depth: GLsizei; fixedsamplelocations: GLboolean); apicall;
  glGetMultisamplefv: procedure (pname: GLenum; index: GLuint; val: PGLfloat); apicall;
  glSampleMaski: procedure (maskNumber: GLuint; mask: GLbitfield); apicall;
  glBindFragDataLocationIndexed: procedure (program_: GLuint; colorNumber: GLuint; index: GLuint; name: PGLchar); apicall;
  glGetFragDataIndex: function (program_: GLuint; name: PGLchar): GLint; apicall;
  glGenSamplers: procedure (count: GLsizei; samplers: PGLuint); apicall;
  glDeleteSamplers: procedure (count: GLsizei; samplers: PGLuint); apicall;
  glIsSampler: function (sampler: GLuint): GLboolean; apicall;
  glBindSampler: procedure (unit_: GLuint; sampler: GLuint); apicall;
  glSamplerParameteri: procedure (sampler: GLuint; pname: GLenum; param: GLint); apicall;
  glSamplerParameteriv: procedure (sampler: GLuint; pname: GLenum; param: PGLint); apicall;
  glSamplerParameterf: procedure (sampler: GLuint; pname: GLenum; param: GLfloat); apicall;
  glSamplerParameterfv: procedure (sampler: GLuint; pname: GLenum; param: PGLfloat); apicall;
  glSamplerParameterIiv: procedure (sampler: GLuint; pname: GLenum; param: PGLint); apicall;
  glSamplerParameterIuiv: procedure (sampler: GLuint; pname: GLenum; param: PGLuint); apicall;
  glGetSamplerParameteriv: procedure (sampler: GLuint; pname: GLenum; params: PGLint); apicall;
  glGetSamplerParameterIiv: procedure (sampler: GLuint; pname: GLenum; params: PGLint); apicall;
  glGetSamplerParameterfv: procedure (sampler: GLuint; pname: GLenum; params: PGLfloat); apicall;
  glGetSamplerParameterIuiv: procedure (sampler: GLuint; pname: GLenum; params: PGLuint); apicall;
  glQueryCounter: procedure (id: GLuint; target: GLenum); apicall;
  glGetQueryObjecti64v: procedure (id: GLuint; pname: GLenum; params: PGLint64); apicall;
  glGetQueryObjectui64v: procedure (id: GLuint; pname: GLenum; params: PGLuint64); apicall;
  glVertexAttribDivisor: procedure (index: GLuint; divisor: GLuint); apicall;
  glVertexAttribP1ui: procedure (index: GLuint; type_: GLenum; normalized: GLboolean; value: GLuint); apicall;
  glVertexAttribP1uiv: procedure (index: GLuint; type_: GLenum; normalized: GLboolean; value: PGLuint); apicall;
  glVertexAttribP2ui: procedure (index: GLuint; type_: GLenum; normalized: GLboolean; value: GLuint); apicall;
  glVertexAttribP2uiv: procedure (index: GLuint; type_: GLenum; normalized: GLboolean; value: PGLuint); apicall;
  glVertexAttribP3ui: procedure (index: GLuint; type_: GLenum; normalized: GLboolean; value: GLuint); apicall;
  glVertexAttribP3uiv: procedure (index: GLuint; type_: GLenum; normalized: GLboolean; value: PGLuint); apicall;
  glVertexAttribP4ui: procedure (index: GLuint; type_: GLenum; normalized: GLboolean; value: GLuint); apicall;
  glVertexAttribP4uiv: procedure (index: GLuint; type_: GLenum; normalized: GLboolean; value: PGLuint); apicall;
  glVertexP2ui: procedure (type_: GLenum; value: GLuint); apicall;
  glVertexP2uiv: procedure (type_: GLenum; value: PGLuint); apicall;
  glVertexP3ui: procedure (type_: GLenum; value: GLuint); apicall;
  glVertexP3uiv: procedure (type_: GLenum; value: PGLuint); apicall;
  glVertexP4ui: procedure (type_: GLenum; value: GLuint); apicall;
  glVertexP4uiv: procedure (type_: GLenum; value: PGLuint); apicall;
  glTexCoordP1ui: procedure (type_: GLenum; coords: GLuint); apicall;
  glTexCoordP1uiv: procedure (type_: GLenum; coords: PGLuint); apicall;
  glTexCoordP2ui: procedure (type_: GLenum; coords: GLuint); apicall;
  glTexCoordP2uiv: procedure (type_: GLenum; coords: PGLuint); apicall;
  glTexCoordP3ui: procedure (type_: GLenum; coords: GLuint); apicall;
  glTexCoordP3uiv: procedure (type_: GLenum; coords: PGLuint); apicall;
  glTexCoordP4ui: procedure (type_: GLenum; coords: GLuint); apicall;
  glTexCoordP4uiv: procedure (type_: GLenum; coords: PGLuint); apicall;
  glMultiTexCoordP1ui: procedure (texture: GLenum; type_: GLenum; coords: GLuint); apicall;
  glMultiTexCoordP1uiv: procedure (texture: GLenum; type_: GLenum; coords: PGLuint); apicall;
  glMultiTexCoordP2ui: procedure (texture: GLenum; type_: GLenum; coords: GLuint); apicall;
  glMultiTexCoordP2uiv: procedure (texture: GLenum; type_: GLenum; coords: PGLuint); apicall;
  glMultiTexCoordP3ui: procedure (texture: GLenum; type_: GLenum; coords: GLuint); apicall;
  glMultiTexCoordP3uiv: procedure (texture: GLenum; type_: GLenum; coords: PGLuint); apicall;
  glMultiTexCoordP4ui: procedure (texture: GLenum; type_: GLenum; coords: GLuint); apicall;
  glMultiTexCoordP4uiv: procedure (texture: GLenum; type_: GLenum; coords: PGLuint); apicall;
  glNormalP3ui: procedure (type_: GLenum; coords: GLuint); apicall;
  glNormalP3uiv: procedure (type_: GLenum; coords: PGLuint); apicall;
  glColorP3ui: procedure (type_: GLenum; color: GLuint); apicall;
  glColorP3uiv: procedure (type_: GLenum; color: PGLuint); apicall;
  glColorP4ui: procedure (type_: GLenum; color: GLuint); apicall;
  glColorP4uiv: procedure (type_: GLenum; color: PGLuint); apicall;
  glSecondaryColorP3ui: procedure (type_: GLenum; color: GLuint); apicall;
  glSecondaryColorP3uiv: procedure (type_: GLenum; color: PGLuint); apicall;


function gladLoadGL: Boolean;

implementation

uses
  Raylib.Glfw;

type
  TLoadProc = function(const procname: PAnsiChar): TGLFWglproc; cdecl;

{$DEFINE HAS_GL_NUM_EXTENSIONS}function hasExt(const extname: string): Boolean;
var
  extensions: PChar;
  loc, terminator: Pchar;
{$IFDEF HAS_GL_NUM_EXTENSIONS}
  num_extensions, i: integer;
  ext: pchar;
{$ENDIF}
begin
  result := false;
{$IFDEF HAS_GL_NUM_EXTENSIONS}
  if glVersionMajor >= 3 then begin
      glGetIntegerv(GL_NUM_EXTENSIONS, @num_extensions);
      for i := 0 to num_extensions - 1 do begin
          ext := PChar( glGetStringi(GL_EXTENSIONS, i) );
          if strcomp(ext, PChar(extname)) = 0 then
              exit(true);
      end;
      exit;
  end;
{$ENDIF}
  extensions := PChar( glGetString(GL_EXTENSIONS) );
  while true do begin
      loc := strpos(extensions, PChar(extname));
      if loc = nil then
          exit;
      terminator := loc + length(extname);
      if (loc = extensions) or (loc[-1] = ' ') then
          if (terminator[0] = ' ') or (terminator[0] = #0) then
              exit(true);
      extensions := terminator;
  end;
end;

procedure load_GL_VERSION_1_0(load: TLoadProc);
begin
  if not GLAD_GL_VERSION_1_0 then exit;
  glCullFace := load('glCullFace');
  glFrontFace := load('glFrontFace');
  glHint := load('glHint');
  glLineWidth := load('glLineWidth');
  glPointSize := load('glPointSize');
  glPolygonMode := load('glPolygonMode');
  glScissor := load('glScissor');
  glTexParameterf := load('glTexParameterf');
  glTexParameterfv := load('glTexParameterfv');
  glTexParameteri := load('glTexParameteri');
  glTexParameteriv := load('glTexParameteriv');
  glTexImage1D := load('glTexImage1D');
  glTexImage2D := load('glTexImage2D');
  glDrawBuffer := load('glDrawBuffer');
  glClear := load('glClear');
  glClearColor := load('glClearColor');
  glClearStencil := load('glClearStencil');
  glClearDepth := load('glClearDepth');
  glStencilMask := load('glStencilMask');
  glColorMask := load('glColorMask');
  glDepthMask := load('glDepthMask');
  glDisable := load('glDisable');
  glEnable := load('glEnable');
  glFinish := load('glFinish');
  glFlush := load('glFlush');
  glBlendFunc := load('glBlendFunc');
  glLogicOp := load('glLogicOp');
  glStencilFunc := load('glStencilFunc');
  glStencilOp := load('glStencilOp');
  glDepthFunc := load('glDepthFunc');
  glPixelStoref := load('glPixelStoref');
  glPixelStorei := load('glPixelStorei');
  glReadBuffer := load('glReadBuffer');
  glReadPixels := load('glReadPixels');
  glGetBooleanv := load('glGetBooleanv');
  glGetDoublev := load('glGetDoublev');
  glGetError := load('glGetError');
  glGetFloatv := load('glGetFloatv');
  glGetIntegerv := load('glGetIntegerv');
  glGetString := load('glGetString');
  glGetTexImage := load('glGetTexImage');
  glGetTexParameterfv := load('glGetTexParameterfv');
  glGetTexParameteriv := load('glGetTexParameteriv');
  glGetTexLevelParameterfv := load('glGetTexLevelParameterfv');
  glGetTexLevelParameteriv := load('glGetTexLevelParameteriv');
  glIsEnabled := load('glIsEnabled');
  glDepthRange := load('glDepthRange');
  glViewport := load('glViewport');
end;

procedure load_GL_VERSION_1_1(load: TLoadProc);
begin
  if not GLAD_GL_VERSION_1_1 then exit;
  glDrawArrays := load('glDrawArrays');
  glDrawElements := load('glDrawElements');
  glPolygonOffset := load('glPolygonOffset');
  glCopyTexImage1D := load('glCopyTexImage1D');
  glCopyTexImage2D := load('glCopyTexImage2D');
  glCopyTexSubImage1D := load('glCopyTexSubImage1D');
  glCopyTexSubImage2D := load('glCopyTexSubImage2D');
  glTexSubImage1D := load('glTexSubImage1D');
  glTexSubImage2D := load('glTexSubImage2D');
  glBindTexture := load('glBindTexture');
  glDeleteTextures := load('glDeleteTextures');
  glGenTextures := load('glGenTextures');
  glIsTexture := load('glIsTexture');
end;

procedure load_GL_VERSION_1_2(load: TLoadProc);
begin
  if not GLAD_GL_VERSION_1_2 then exit;
  glDrawRangeElements := load('glDrawRangeElements');
  glTexImage3D := load('glTexImage3D');
  glTexSubImage3D := load('glTexSubImage3D');
  glCopyTexSubImage3D := load('glCopyTexSubImage3D');
end;

procedure load_GL_VERSION_1_3(load: TLoadProc);
begin
  if not GLAD_GL_VERSION_1_3 then exit;
  glActiveTexture := load('glActiveTexture');
  glSampleCoverage := load('glSampleCoverage');
  glCompressedTexImage3D := load('glCompressedTexImage3D');
  glCompressedTexImage2D := load('glCompressedTexImage2D');
  glCompressedTexImage1D := load('glCompressedTexImage1D');
  glCompressedTexSubImage3D := load('glCompressedTexSubImage3D');
  glCompressedTexSubImage2D := load('glCompressedTexSubImage2D');
  glCompressedTexSubImage1D := load('glCompressedTexSubImage1D');
  glGetCompressedTexImage := load('glGetCompressedTexImage');
end;

procedure load_GL_VERSION_1_4(load: TLoadProc);
begin
  if not GLAD_GL_VERSION_1_4 then exit;
  glBlendFuncSeparate := load('glBlendFuncSeparate');
  glMultiDrawArrays := load('glMultiDrawArrays');
  glMultiDrawElements := load('glMultiDrawElements');
  glPointParameterf := load('glPointParameterf');
  glPointParameterfv := load('glPointParameterfv');
  glPointParameteri := load('glPointParameteri');
  glPointParameteriv := load('glPointParameteriv');
  glBlendColor := load('glBlendColor');
  glBlendEquation := load('glBlendEquation');
end;

procedure load_GL_VERSION_1_5(load: TLoadProc);
begin
  if not GLAD_GL_VERSION_1_5 then exit;
  glGenQueries := load('glGenQueries');
  glDeleteQueries := load('glDeleteQueries');
  glIsQuery := load('glIsQuery');
  glBeginQuery := load('glBeginQuery');
  glEndQuery := load('glEndQuery');
  glGetQueryiv := load('glGetQueryiv');
  glGetQueryObjectiv := load('glGetQueryObjectiv');
  glGetQueryObjectuiv := load('glGetQueryObjectuiv');
  glBindBuffer := load('glBindBuffer');
  glDeleteBuffers := load('glDeleteBuffers');
  glGenBuffers := load('glGenBuffers');
  glIsBuffer := load('glIsBuffer');
  glBufferData := load('glBufferData');
  glBufferSubData := load('glBufferSubData');
  glGetBufferSubData := load('glGetBufferSubData');
  glMapBuffer := load('glMapBuffer');
  glUnmapBuffer := load('glUnmapBuffer');
  glGetBufferParameteriv := load('glGetBufferParameteriv');
  glGetBufferPointerv := load('glGetBufferPointerv');
end;

procedure load_GL_VERSION_2_0(load: TLoadProc);
begin
  if not GLAD_GL_VERSION_2_0 then exit;
  glBlendEquationSeparate := load('glBlendEquationSeparate');
  glDrawBuffers := load('glDrawBuffers');
  glStencilOpSeparate := load('glStencilOpSeparate');
  glStencilFuncSeparate := load('glStencilFuncSeparate');
  glStencilMaskSeparate := load('glStencilMaskSeparate');
  glAttachShader := load('glAttachShader');
  glBindAttribLocation := load('glBindAttribLocation');
  glCompileShader := load('glCompileShader');
  glCreateProgram := load('glCreateProgram');
  glCreateShader := load('glCreateShader');
  glDeleteProgram := load('glDeleteProgram');
  glDeleteShader := load('glDeleteShader');
  glDetachShader := load('glDetachShader');
  glDisableVertexAttribArray := load('glDisableVertexAttribArray');
  glEnableVertexAttribArray := load('glEnableVertexAttribArray');
  glGetActiveAttrib := load('glGetActiveAttrib');
  glGetActiveUniform := load('glGetActiveUniform');
  glGetAttachedShaders := load('glGetAttachedShaders');
  glGetAttribLocation := load('glGetAttribLocation');
  glGetProgramiv := load('glGetProgramiv');
  glGetProgramInfoLog := load('glGetProgramInfoLog');
  glGetShaderiv := load('glGetShaderiv');
  glGetShaderInfoLog := load('glGetShaderInfoLog');
  glGetShaderSource := load('glGetShaderSource');
  glGetUniformLocation := load('glGetUniformLocation');
  glGetUniformfv := load('glGetUniformfv');
  glGetUniformiv := load('glGetUniformiv');
  glGetVertexAttribdv := load('glGetVertexAttribdv');
  glGetVertexAttribfv := load('glGetVertexAttribfv');
  glGetVertexAttribiv := load('glGetVertexAttribiv');
  glGetVertexAttribPointerv := load('glGetVertexAttribPointerv');
  glIsProgram := load('glIsProgram');
  glIsShader := load('glIsShader');
  glLinkProgram := load('glLinkProgram');
  glShaderSource := load('glShaderSource');
  glUseProgram := load('glUseProgram');
  glUniform1f := load('glUniform1f');
  glUniform2f := load('glUniform2f');
  glUniform3f := load('glUniform3f');
  glUniform4f := load('glUniform4f');
  glUniform1i := load('glUniform1i');
  glUniform2i := load('glUniform2i');
  glUniform3i := load('glUniform3i');
  glUniform4i := load('glUniform4i');
  glUniform1fv := load('glUniform1fv');
  glUniform2fv := load('glUniform2fv');
  glUniform3fv := load('glUniform3fv');
  glUniform4fv := load('glUniform4fv');
  glUniform1iv := load('glUniform1iv');
  glUniform2iv := load('glUniform2iv');
  glUniform3iv := load('glUniform3iv');
  glUniform4iv := load('glUniform4iv');
  glUniformMatrix2fv := load('glUniformMatrix2fv');
  glUniformMatrix3fv := load('glUniformMatrix3fv');
  glUniformMatrix4fv := load('glUniformMatrix4fv');
  glValidateProgram := load('glValidateProgram');
  glVertexAttrib1d := load('glVertexAttrib1d');
  glVertexAttrib1dv := load('glVertexAttrib1dv');
  glVertexAttrib1f := load('glVertexAttrib1f');
  glVertexAttrib1fv := load('glVertexAttrib1fv');
  glVertexAttrib1s := load('glVertexAttrib1s');
  glVertexAttrib1sv := load('glVertexAttrib1sv');
  glVertexAttrib2d := load('glVertexAttrib2d');
  glVertexAttrib2dv := load('glVertexAttrib2dv');
  glVertexAttrib2f := load('glVertexAttrib2f');
  glVertexAttrib2fv := load('glVertexAttrib2fv');
  glVertexAttrib2s := load('glVertexAttrib2s');
  glVertexAttrib2sv := load('glVertexAttrib2sv');
  glVertexAttrib3d := load('glVertexAttrib3d');
  glVertexAttrib3dv := load('glVertexAttrib3dv');
  glVertexAttrib3f := load('glVertexAttrib3f');
  glVertexAttrib3fv := load('glVertexAttrib3fv');
  glVertexAttrib3s := load('glVertexAttrib3s');
  glVertexAttrib3sv := load('glVertexAttrib3sv');
  glVertexAttrib4Nbv := load('glVertexAttrib4Nbv');
  glVertexAttrib4Niv := load('glVertexAttrib4Niv');
  glVertexAttrib4Nsv := load('glVertexAttrib4Nsv');
  glVertexAttrib4Nub := load('glVertexAttrib4Nub');
  glVertexAttrib4Nubv := load('glVertexAttrib4Nubv');
  glVertexAttrib4Nuiv := load('glVertexAttrib4Nuiv');
  glVertexAttrib4Nusv := load('glVertexAttrib4Nusv');
  glVertexAttrib4bv := load('glVertexAttrib4bv');
  glVertexAttrib4d := load('glVertexAttrib4d');
  glVertexAttrib4dv := load('glVertexAttrib4dv');
  glVertexAttrib4f := load('glVertexAttrib4f');
  glVertexAttrib4fv := load('glVertexAttrib4fv');
  glVertexAttrib4iv := load('glVertexAttrib4iv');
  glVertexAttrib4s := load('glVertexAttrib4s');
  glVertexAttrib4sv := load('glVertexAttrib4sv');
  glVertexAttrib4ubv := load('glVertexAttrib4ubv');
  glVertexAttrib4uiv := load('glVertexAttrib4uiv');
  glVertexAttrib4usv := load('glVertexAttrib4usv');
  glVertexAttribPointer := load('glVertexAttribPointer');
end;

procedure load_GL_VERSION_2_1(load: TLoadProc);
begin
  if not GLAD_GL_VERSION_2_1 then exit;
  glUniformMatrix2x3fv := load('glUniformMatrix2x3fv');
  glUniformMatrix3x2fv := load('glUniformMatrix3x2fv');
  glUniformMatrix2x4fv := load('glUniformMatrix2x4fv');
  glUniformMatrix4x2fv := load('glUniformMatrix4x2fv');
  glUniformMatrix3x4fv := load('glUniformMatrix3x4fv');
  glUniformMatrix4x3fv := load('glUniformMatrix4x3fv');
end;

procedure load_GL_VERSION_3_0(load: TLoadProc);
begin
  if not GLAD_GL_VERSION_3_0 then exit;
  glColorMaski := load('glColorMaski');
  glGetBooleani_v := load('glGetBooleani_v');
  glGetIntegeri_v := load('glGetIntegeri_v');
  glEnablei := load('glEnablei');
  glDisablei := load('glDisablei');
  glIsEnabledi := load('glIsEnabledi');
  glBeginTransformFeedback := load('glBeginTransformFeedback');
  glEndTransformFeedback := load('glEndTransformFeedback');
  glBindBufferRange := load('glBindBufferRange');
  glBindBufferBase := load('glBindBufferBase');
  glTransformFeedbackVaryings := load('glTransformFeedbackVaryings');
  glGetTransformFeedbackVarying := load('glGetTransformFeedbackVarying');
  glClampColor := load('glClampColor');
  glBeginConditionalRender := load('glBeginConditionalRender');
  glEndConditionalRender := load('glEndConditionalRender');
  glVertexAttribIPointer := load('glVertexAttribIPointer');
  glGetVertexAttribIiv := load('glGetVertexAttribIiv');
  glGetVertexAttribIuiv := load('glGetVertexAttribIuiv');
  glVertexAttribI1i := load('glVertexAttribI1i');
  glVertexAttribI2i := load('glVertexAttribI2i');
  glVertexAttribI3i := load('glVertexAttribI3i');
  glVertexAttribI4i := load('glVertexAttribI4i');
  glVertexAttribI1ui := load('glVertexAttribI1ui');
  glVertexAttribI2ui := load('glVertexAttribI2ui');
  glVertexAttribI3ui := load('glVertexAttribI3ui');
  glVertexAttribI4ui := load('glVertexAttribI4ui');
  glVertexAttribI1iv := load('glVertexAttribI1iv');
  glVertexAttribI2iv := load('glVertexAttribI2iv');
  glVertexAttribI3iv := load('glVertexAttribI3iv');
  glVertexAttribI4iv := load('glVertexAttribI4iv');
  glVertexAttribI1uiv := load('glVertexAttribI1uiv');
  glVertexAttribI2uiv := load('glVertexAttribI2uiv');
  glVertexAttribI3uiv := load('glVertexAttribI3uiv');
  glVertexAttribI4uiv := load('glVertexAttribI4uiv');
  glVertexAttribI4bv := load('glVertexAttribI4bv');
  glVertexAttribI4sv := load('glVertexAttribI4sv');
  glVertexAttribI4ubv := load('glVertexAttribI4ubv');
  glVertexAttribI4usv := load('glVertexAttribI4usv');
  glGetUniformuiv := load('glGetUniformuiv');
  glBindFragDataLocation := load('glBindFragDataLocation');
  glGetFragDataLocation := load('glGetFragDataLocation');
  glUniform1ui := load('glUniform1ui');
  glUniform2ui := load('glUniform2ui');
  glUniform3ui := load('glUniform3ui');
  glUniform4ui := load('glUniform4ui');
  glUniform1uiv := load('glUniform1uiv');
  glUniform2uiv := load('glUniform2uiv');
  glUniform3uiv := load('glUniform3uiv');
  glUniform4uiv := load('glUniform4uiv');
  glTexParameterIiv := load('glTexParameterIiv');
  glTexParameterIuiv := load('glTexParameterIuiv');
  glGetTexParameterIiv := load('glGetTexParameterIiv');
  glGetTexParameterIuiv := load('glGetTexParameterIuiv');
  glClearBufferiv := load('glClearBufferiv');
  glClearBufferuiv := load('glClearBufferuiv');
  glClearBufferfv := load('glClearBufferfv');
  glClearBufferfi := load('glClearBufferfi');
  glGetStringi := load('glGetStringi');
  glIsRenderbuffer := load('glIsRenderbuffer');
  glBindRenderbuffer := load('glBindRenderbuffer');
  glDeleteRenderbuffers := load('glDeleteRenderbuffers');
  glGenRenderbuffers := load('glGenRenderbuffers');
  glRenderbufferStorage := load('glRenderbufferStorage');
  glGetRenderbufferParameteriv := load('glGetRenderbufferParameteriv');
  glIsFramebuffer := load('glIsFramebuffer');
  glBindFramebuffer := load('glBindFramebuffer');
  glDeleteFramebuffers := load('glDeleteFramebuffers');
  glGenFramebuffers := load('glGenFramebuffers');
  glCheckFramebufferStatus := load('glCheckFramebufferStatus');
  glFramebufferTexture1D := load('glFramebufferTexture1D');
  glFramebufferTexture2D := load('glFramebufferTexture2D');
  glFramebufferTexture3D := load('glFramebufferTexture3D');
  glFramebufferRenderbuffer := load('glFramebufferRenderbuffer');
  glGetFramebufferAttachmentParameteriv := load('glGetFramebufferAttachmentParameteriv');
  glGenerateMipmap := load('glGenerateMipmap');
  glBlitFramebuffer := load('glBlitFramebuffer');
  glRenderbufferStorageMultisample := load('glRenderbufferStorageMultisample');
  glFramebufferTextureLayer := load('glFramebufferTextureLayer');
  glMapBufferRange := load('glMapBufferRange');
  glFlushMappedBufferRange := load('glFlushMappedBufferRange');
  glBindVertexArray := load('glBindVertexArray');
  glDeleteVertexArrays := load('glDeleteVertexArrays');
  glGenVertexArrays := load('glGenVertexArrays');
  glIsVertexArray := load('glIsVertexArray');
end;

procedure load_GL_VERSION_3_1(load: TLoadProc);
begin
  if not GLAD_GL_VERSION_3_1 then exit;
  glDrawArraysInstanced := load('glDrawArraysInstanced');
  glDrawElementsInstanced := load('glDrawElementsInstanced');
  glTexBuffer := load('glTexBuffer');
  glPrimitiveRestartIndex := load('glPrimitiveRestartIndex');
  glCopyBufferSubData := load('glCopyBufferSubData');
  glGetUniformIndices := load('glGetUniformIndices');
  glGetActiveUniformsiv := load('glGetActiveUniformsiv');
  glGetActiveUniformName := load('glGetActiveUniformName');
  glGetUniformBlockIndex := load('glGetUniformBlockIndex');
  glGetActiveUniformBlockiv := load('glGetActiveUniformBlockiv');
  glGetActiveUniformBlockName := load('glGetActiveUniformBlockName');
  glUniformBlockBinding := load('glUniformBlockBinding');
  glBindBufferRange := load('glBindBufferRange');
  glBindBufferBase := load('glBindBufferBase');
  glGetIntegeri_v := load('glGetIntegeri_v');
end;

procedure load_GL_VERSION_3_2(load: TLoadProc);
begin
  if not GLAD_GL_VERSION_3_2 then exit;
  glDrawElementsBaseVertex := load('glDrawElementsBaseVertex');
  glDrawRangeElementsBaseVertex := load('glDrawRangeElementsBaseVertex');
  glDrawElementsInstancedBaseVertex := load('glDrawElementsInstancedBaseVertex');
  glMultiDrawElementsBaseVertex := load('glMultiDrawElementsBaseVertex');
  glProvokingVertex := load('glProvokingVertex');
  glFenceSync := load('glFenceSync');
  glIsSync := load('glIsSync');
  glDeleteSync := load('glDeleteSync');
  glClientWaitSync := load('glClientWaitSync');
  glWaitSync := load('glWaitSync');
  glGetInteger64v := load('glGetInteger64v');
  glGetSynciv := load('glGetSynciv');
  glGetInteger64i_v := load('glGetInteger64i_v');
  glGetBufferParameteri64v := load('glGetBufferParameteri64v');
  glFramebufferTexture := load('glFramebufferTexture');
  glTexImage2DMultisample := load('glTexImage2DMultisample');
  glTexImage3DMultisample := load('glTexImage3DMultisample');
  glGetMultisamplefv := load('glGetMultisamplefv');
  glSampleMaski := load('glSampleMaski');
end;

procedure load_GL_VERSION_3_3(load: TLoadProc);
begin
  if not GLAD_GL_VERSION_3_3 then exit;
  glBindFragDataLocationIndexed := load('glBindFragDataLocationIndexed');
  glGetFragDataIndex := load('glGetFragDataIndex');
  glGenSamplers := load('glGenSamplers');
  glDeleteSamplers := load('glDeleteSamplers');
  glIsSampler := load('glIsSampler');
  glBindSampler := load('glBindSampler');
  glSamplerParameteri := load('glSamplerParameteri');
  glSamplerParameteriv := load('glSamplerParameteriv');
  glSamplerParameterf := load('glSamplerParameterf');
  glSamplerParameterfv := load('glSamplerParameterfv');
  glSamplerParameterIiv := load('glSamplerParameterIiv');
  glSamplerParameterIuiv := load('glSamplerParameterIuiv');
  glGetSamplerParameteriv := load('glGetSamplerParameteriv');
  glGetSamplerParameterIiv := load('glGetSamplerParameterIiv');
  glGetSamplerParameterfv := load('glGetSamplerParameterfv');
  glGetSamplerParameterIuiv := load('glGetSamplerParameterIuiv');
  glQueryCounter := load('glQueryCounter');
  glGetQueryObjecti64v := load('glGetQueryObjecti64v');
  glGetQueryObjectui64v := load('glGetQueryObjectui64v');
  glVertexAttribDivisor := load('glVertexAttribDivisor');
  glVertexAttribP1ui := load('glVertexAttribP1ui');
  glVertexAttribP1uiv := load('glVertexAttribP1uiv');
  glVertexAttribP2ui := load('glVertexAttribP2ui');
  glVertexAttribP2uiv := load('glVertexAttribP2uiv');
  glVertexAttribP3ui := load('glVertexAttribP3ui');
  glVertexAttribP3uiv := load('glVertexAttribP3uiv');
  glVertexAttribP4ui := load('glVertexAttribP4ui');
  glVertexAttribP4uiv := load('glVertexAttribP4uiv');
  glVertexP2ui := load('glVertexP2ui');
  glVertexP2uiv := load('glVertexP2uiv');
  glVertexP3ui := load('glVertexP3ui');
  glVertexP3uiv := load('glVertexP3uiv');
  glVertexP4ui := load('glVertexP4ui');
  glVertexP4uiv := load('glVertexP4uiv');
  glTexCoordP1ui := load('glTexCoordP1ui');
  glTexCoordP1uiv := load('glTexCoordP1uiv');
  glTexCoordP2ui := load('glTexCoordP2ui');
  glTexCoordP2uiv := load('glTexCoordP2uiv');
  glTexCoordP3ui := load('glTexCoordP3ui');
  glTexCoordP3uiv := load('glTexCoordP3uiv');
  glTexCoordP4ui := load('glTexCoordP4ui');
  glTexCoordP4uiv := load('glTexCoordP4uiv');
  glMultiTexCoordP1ui := load('glMultiTexCoordP1ui');
  glMultiTexCoordP1uiv := load('glMultiTexCoordP1uiv');
  glMultiTexCoordP2ui := load('glMultiTexCoordP2ui');
  glMultiTexCoordP2uiv := load('glMultiTexCoordP2uiv');
  glMultiTexCoordP3ui := load('glMultiTexCoordP3ui');
  glMultiTexCoordP3uiv := load('glMultiTexCoordP3uiv');
  glMultiTexCoordP4ui := load('glMultiTexCoordP4ui');
  glMultiTexCoordP4uiv := load('glMultiTexCoordP4uiv');
  glNormalP3ui := load('glNormalP3ui');
  glNormalP3uiv := load('glNormalP3uiv');
  glColorP3ui := load('glColorP3ui');
  glColorP3uiv := load('glColorP3uiv');
  glColorP4ui := load('glColorP4ui');
  glColorP4uiv := load('glColorP4uiv');
  glSecondaryColorP3ui := load('glSecondaryColorP3ui');
  glSecondaryColorP3uiv := load('glSecondaryColorP3uiv');
end;

procedure findCoreGL(glVersion: string);
{ Thank you @elmindreda
  https://github.com/elmindreda/greg/blob/master/templates/greg.c.in//L176
  https://github.com/glfw/glfw/blob/master/src/context.c//L36 }
const
  prefixes: array[0..2] of string = ('OpenGL ES-CM ', 'OpenGL ES-CL ', 'OpenGL ES ');
var
  version, p: string;
  major, minor: integer;
begin
  version := glVersion;
  for p in prefixes do
    if LeftStr(version, length(p)) = p then begin
      version := StringReplace(version, p, '', [rfReplaceAll]);
      break;
    end;

  major := ord(version[1]) - ord('0');
  minor := ord(version[3]) - ord('0');

  glVersionMajor := major;
  glVersionMinor := minor;

  GLAD_GL_VERSION_1_0 := ((major = 1) and (minor >= 0)) or (major > 1);
  GLAD_GL_VERSION_1_1 := ((major = 1) and (minor >= 1)) or (major > 1);
  GLAD_GL_VERSION_1_2 := ((major = 1) and (minor >= 2)) or (major > 1);
  GLAD_GL_VERSION_1_3 := ((major = 1) and (minor >= 3)) or (major > 1);
  GLAD_GL_VERSION_1_4 := ((major = 1) and (minor >= 4)) or (major > 1);
  GLAD_GL_VERSION_1_5 := ((major = 1) and (minor >= 5)) or (major > 1);
  GLAD_GL_VERSION_2_0 := ((major = 2) and (minor >= 0)) or (major > 2);
  GLAD_GL_VERSION_2_1 := ((major = 2) and (minor >= 1)) or (major > 2);
  GLAD_GL_VERSION_3_0 := ((major = 3) and (minor >= 0)) or (major > 3);
  GLAD_GL_VERSION_3_1 := ((major = 3) and (minor >= 1)) or (major > 3);
  GLAD_GL_VERSION_3_2 := ((major = 3) and (minor >= 2)) or (major > 3);
  GLAD_GL_VERSION_3_3 := ((major = 3) and (minor >= 3)) or (major > 3);
end;

var
  gladLoaded: Boolean;
  gladSuccess: Boolean;

function gladLoadGL: Boolean;
var
  glVersion: PAnsiChar;
begin
  Result := gladSuccess;
  if gladLoaded then
    Exit;
  gladLoaded := True;
  glGetString := glfwGetProcAddress('glGetString');
  if not Assigned(glGetString) then
    Exit;
  glVersion := PAnsiChar(glGetString(GL_VERSION));
  if glVersion = nil then
    Exit;
  findCoreGL(glVersion);
  load_GL_VERSION_1_0(glfwGetProcAddress);
  load_GL_VERSION_1_1(glfwGetProcAddress);
  load_GL_VERSION_1_2(glfwGetProcAddress);
  load_GL_VERSION_1_3(glfwGetProcAddress);
  load_GL_VERSION_1_4(glfwGetProcAddress);
  load_GL_VERSION_1_5(glfwGetProcAddress);
  load_GL_VERSION_2_0(glfwGetProcAddress);
  load_GL_VERSION_2_1(glfwGetProcAddress);
  load_GL_VERSION_3_0(glfwGetProcAddress);
  load_GL_VERSION_3_1(glfwGetProcAddress);
  load_GL_VERSION_3_2(glfwGetProcAddress);
  load_GL_VERSION_3_3(glfwGetProcAddress);
  gladSuccess := (glVersionMajor <> 0) or (glVersionMinor <> 0);
  Result := gladSuccess;
end;

end.

